function asyncGeneratorStep(gen,resolve,reject,_next,_throw,key,arg){try{var info=gen[key](arg);var value=info.value}catch(error){reject(error);return}if(info.done)resolve(value);else Promise.resolve(value).then(_next,_throw)}
function _asyncToGenerator(fn){return function(){var self=this,args=arguments;return new Promise(function(resolve,reject){var gen=fn.apply(self,args);function _next(value){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"next",value)}function _throw(err){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"throw",err)}_next(undefined)})}}
function _defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor)}}
function _createClass(Constructor,protoProps,staticProps){if(protoProps)_defineProperties(Constructor.prototype,protoProps);if(staticProps)_defineProperties(Constructor,staticProps);Object.defineProperty(Constructor,"prototype",{writable:false});return Constructor}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor))throw new TypeError("Cannot call a class as a function");}var LineHighlighter=InteractiveExample.LineHighlighter;var Timer=InteractiveExample.Timer;
var initExamples=InteractiveExample.initExamples;var VisualTree=InteractiveExample.VisualTree;var VisualVariables=InteractiveExample.VisualVariables;var Node=_createClass(function Node(value){_classCallCheck(this,Node);this.value=value;this.left=null;this.right=null});
var BinarySearchTree=function(){function BinarySearchTree(){_classCallCheck(this,BinarySearchTree);this.root=null}_createClass(BinarySearchTree,[{key:"insert",value:function insert(value){var newNode=new Node(value);if(!this.root){this.root=newNode;return this}var current=this.root;while(true){if(value===current.value)return undefined;if(value>current.value){if(!current.right){current.right=newNode;return this}current=current.right}else{if(!current.left){current.left=newNode;return this}current=current.left}}}},
{key:"find",value:function find(value){if(!this.root)return false;var current=this.root;while(current){if(value===current.value)return current;if(value>current.value)current=current.right;else current=current.left}return false}}]);return BinarySearchTree}();
var config=[{exampleId:1,visualTree:new VisualTree("binary-search-tree-1",["current"]),visualVariables:new VisualVariables([{id:"variable-insert-value",value:0,hide:true}],true),lineHighlighter:new LineHighlighter("code-1"),timer:new Timer,code:function(){var _code=_asyncToGenerator(regeneratorRuntime.mark(function _callee2(){var proceed,tree;return regeneratorRuntime.wrap(function _callee2$(_context2){while(1)switch(_context2.prev=_context2.next){case 0:tree=new BinarySearchTree;tree.exampleInsert=
function(){var _ref=_asyncToGenerator(regeneratorRuntime.mark(function _callee(value,lineHighlighter,timer,visualVariables,visualTree){var newNode,current;return regeneratorRuntime.wrap(function _callee$(_context){while(1)switch(_context.prev=_context.next){case 0:newNode=new Node(value);visualVariables.show("variable-insert-value");visualVariables.setValue("variable-insert-value",value);lineHighlighter.highlight(6);_context.next=6;return timer.wait(500);case 6:proceed=_context.sent;if(proceed){_context.next=
9;break}return _context.abrupt("return");case 9:lineHighlighter.clear();lineHighlighter.highlight(9);_context.next=13;return timer.wait(500);case 13:proceed=_context.sent;if(proceed){_context.next=16;break}return _context.abrupt("return");case 16:lineHighlighter.clear();if(this.root){_context.next=36;break}this.root=newNode;visualTree.insert(value);lineHighlighter.highlight(10);_context.next=23;return timer.wait(500);case 23:proceed=_context.sent;if(proceed){_context.next=26;break}return _context.abrupt("return");
case 26:lineHighlighter.clear();lineHighlighter.highlight(11);_context.next=30;return timer.wait(500);case 30:proceed=_context.sent;if(proceed){_context.next=33;break}return _context.abrupt("return");case 33:lineHighlighter.clear();visualVariables.hide("variable-insert-value");return _context.abrupt("return",this);case 36:current=this.root;visualTree.setPointerToNode("current",this.root.value);lineHighlighter.highlight(15);_context.next=41;return timer.wait(500);case 41:proceed=_context.sent;if(proceed){_context.next=
44;break}return _context.abrupt("return");case 44:lineHighlighter.clear();lineHighlighter.highlight(18);_context.next=48;return timer.wait(500);case 48:proceed=_context.sent;if(proceed){_context.next=51;break}return _context.abrupt("return");case 51:lineHighlighter.clear();case 52:if(!true){_context.next=155;break}lineHighlighter.highlight(22);_context.next=56;return timer.wait(500);case 56:proceed=_context.sent;if(proceed){_context.next=59;break}return _context.abrupt("return");case 59:lineHighlighter.clear();
if(!(value===current.value)){_context.next=64;break}visualVariables.hide("variable-insert-value");visualTree.hidePointer("current");return _context.abrupt("return",undefined);case 64:lineHighlighter.highlight(24);_context.next=67;return timer.wait(500);case 67:proceed=_context.sent;if(proceed){_context.next=70;break}return _context.abrupt("return");case 70:lineHighlighter.clear();if(!(value>current.value)){_context.next=110;break}lineHighlighter.highlight(26);_context.next=75;return timer.wait(500);
case 75:proceed=_context.sent;if(proceed){_context.next=78;break}return _context.abrupt("return");case 78:lineHighlighter.clear();if(current.right){_context.next=99;break}current.right=newNode;visualTree.insert(value);lineHighlighter.highlight(27);_context.next=85;return timer.wait(500);case 85:proceed=_context.sent;if(proceed){_context.next=88;break}return _context.abrupt("return");case 88:lineHighlighter.clear();lineHighlighter.highlight(28);_context.next=92;return timer.wait(500);case 92:proceed=
_context.sent;if(proceed){_context.next=95;break}return _context.abrupt("return");case 95:lineHighlighter.clear();visualVariables.hide("variable-insert-value");visualTree.hidePointer("current");return _context.abrupt("return",this);case 99:current=current.right;visualTree.setPointerToNode("current",current.value);lineHighlighter.highlight(31);_context.next=104;return timer.wait(500);case 104:proceed=_context.sent;if(proceed){_context.next=107;break}return _context.abrupt("return");case 107:lineHighlighter.clear();
_context.next=146;break;case 110:lineHighlighter.highlight(35);_context.next=113;return timer.wait(500);case 113:proceed=_context.sent;if(proceed){_context.next=116;break}return _context.abrupt("return");case 116:lineHighlighter.clear();if(current.left){_context.next=137;break}current.left=newNode;visualTree.insert(value);lineHighlighter.highlight(36);_context.next=123;return timer.wait(500);case 123:proceed=_context.sent;if(proceed){_context.next=126;break}return _context.abrupt("return");case 126:lineHighlighter.clear();
lineHighlighter.highlight(37);_context.next=130;return timer.wait(500);case 130:proceed=_context.sent;if(proceed){_context.next=133;break}return _context.abrupt("return");case 133:lineHighlighter.clear();visualVariables.hide("variable-insert-value");visualTree.hidePointer("current");return _context.abrupt("return",this);case 137:current=current.left;visualTree.setPointerToNode("current",current.value);lineHighlighter.highlight(40);_context.next=142;return timer.wait(500);case 142:proceed=_context.sent;
if(proceed){_context.next=145;break}return _context.abrupt("return");case 145:lineHighlighter.clear();case 146:lineHighlighter.highlight(18);_context.next=149;return timer.wait(500);case 149:proceed=_context.sent;if(proceed){_context.next=152;break}return _context.abrupt("return");case 152:lineHighlighter.clear();_context.next=52;break;case 155:case "end":return _context.stop()}},_callee,this)}));return function(_x,_x2,_x3,_x4,_x5){return _ref.apply(this,arguments)}}();this.lineHighlighter.highlight(47);
_context2.next=5;return this.timer.wait(500);case 5:proceed=_context2.sent;if(proceed){_context2.next=8;break}return _context2.abrupt("return");case 8:this.lineHighlighter.clear();this.lineHighlighter.highlight(49);_context2.next=12;return this.timer.wait(500);case 12:proceed=_context2.sent;if(proceed){_context2.next=15;break}return _context2.abrupt("return");case 15:this.lineHighlighter.clear();_context2.next=18;return tree.exampleInsert(10,this.lineHighlighter,this.timer,this.visualVariables,this.visualTree);
case 18:if(proceed){_context2.next=20;break}return _context2.abrupt("return");case 20:this.lineHighlighter.highlight(49);_context2.next=23;return this.timer.wait(500);case 23:proceed=_context2.sent;if(proceed){_context2.next=26;break}return _context2.abrupt("return");case 26:this.lineHighlighter.clear();this.lineHighlighter.highlight(50);_context2.next=30;return this.timer.wait(500);case 30:proceed=_context2.sent;if(proceed){_context2.next=33;break}return _context2.abrupt("return");case 33:this.lineHighlighter.clear();
_context2.next=36;return tree.exampleInsert(5,this.lineHighlighter,this.timer,this.visualVariables,this.visualTree);case 36:if(proceed){_context2.next=38;break}return _context2.abrupt("return");case 38:this.lineHighlighter.highlight(50);_context2.next=41;return this.timer.wait(500);case 41:proceed=_context2.sent;if(proceed){_context2.next=44;break}return _context2.abrupt("return");case 44:this.lineHighlighter.clear();this.lineHighlighter.highlight(51);_context2.next=48;return this.timer.wait(500);
case 48:proceed=_context2.sent;if(proceed){_context2.next=51;break}return _context2.abrupt("return");case 51:this.lineHighlighter.clear();_context2.next=54;return tree.exampleInsert(13,this.lineHighlighter,this.timer,this.visualVariables,this.visualTree);case 54:if(proceed){_context2.next=56;break}return _context2.abrupt("return");case 56:this.lineHighlighter.highlight(51);_context2.next=59;return this.timer.wait(500);case 59:proceed=_context2.sent;if(proceed){_context2.next=62;break}return _context2.abrupt("return");
case 62:this.lineHighlighter.clear();this.lineHighlighter.highlight(52);_context2.next=66;return this.timer.wait(500);case 66:proceed=_context2.sent;if(proceed){_context2.next=69;break}return _context2.abrupt("return");case 69:this.lineHighlighter.clear();_context2.next=72;return tree.exampleInsert(11,this.lineHighlighter,this.timer,this.visualVariables,this.visualTree);case 72:if(proceed){_context2.next=74;break}return _context2.abrupt("return");case 74:this.lineHighlighter.highlight(52);_context2.next=
77;return this.timer.wait(500);case 77:proceed=_context2.sent;if(proceed){_context2.next=80;break}return _context2.abrupt("return");case 80:this.lineHighlighter.clear();this.lineHighlighter.highlight(53);_context2.next=84;return this.timer.wait(500);case 84:proceed=_context2.sent;if(proceed){_context2.next=87;break}return _context2.abrupt("return");case 87:this.lineHighlighter.clear();_context2.next=90;return tree.exampleInsert(2,this.lineHighlighter,this.timer,this.visualVariables,this.visualTree);
case 90:if(proceed){_context2.next=92;break}return _context2.abrupt("return");case 92:this.lineHighlighter.highlight(53);_context2.next=95;return this.timer.wait(500);case 95:proceed=_context2.sent;if(proceed){_context2.next=98;break}return _context2.abrupt("return");case 98:this.lineHighlighter.clear();this.lineHighlighter.highlight(54);_context2.next=102;return this.timer.wait(500);case 102:proceed=_context2.sent;if(proceed){_context2.next=105;break}return _context2.abrupt("return");case 105:this.lineHighlighter.clear();
_context2.next=108;return tree.exampleInsert(16,this.lineHighlighter,this.timer,this.visualVariables,this.visualTree);case 108:if(proceed){_context2.next=110;break}return _context2.abrupt("return");case 110:this.lineHighlighter.highlight(54);_context2.next=113;return this.timer.wait(500);case 113:proceed=_context2.sent;if(proceed){_context2.next=116;break}return _context2.abrupt("return");case 116:this.lineHighlighter.clear();this.lineHighlighter.highlight(55);_context2.next=120;return this.timer.wait(500);
case 120:proceed=_context2.sent;if(proceed){_context2.next=123;break}return _context2.abrupt("return");case 123:this.lineHighlighter.clear();_context2.next=126;return tree.exampleInsert(7,this.lineHighlighter,this.timer,this.visualVariables,this.visualTree);case 126:if(proceed){_context2.next=128;break}return _context2.abrupt("return");case 128:this.lineHighlighter.highlight(55);_context2.next=131;return this.timer.wait(500);case 131:proceed=_context2.sent;if(proceed){_context2.next=134;break}return _context2.abrupt("return");
case 134:this.lineHighlighter.clear();this.lineHighlighter.highlight(56);_context2.next=138;return this.timer.wait(500);case 138:proceed=_context2.sent;if(proceed){_context2.next=141;break}return _context2.abrupt("return");case 141:this.lineHighlighter.clear();_context2.next=144;return tree.exampleInsert(3,this.lineHighlighter,this.timer,this.visualVariables,this.visualTree);case 144:if(proceed){_context2.next=146;break}return _context2.abrupt("return");case 146:this.lineHighlighter.highlight(56);
_context2.next=149;return this.timer.wait(500);case 149:proceed=_context2.sent;if(proceed){_context2.next=152;break}return _context2.abrupt("return");case 152:this.lineHighlighter.clear();this.finish();case 154:case "end":return _context2.stop()}},_callee2,this)}));function code(){return _code.apply(this,arguments)}return code}()},{exampleId:2,visualTree:new VisualTree("binary-search-tree-2",["current","vyhledanaNode1","vyhledanaNode2"]),visualVariables:new VisualVariables([{id:"variable-find-value",
value:0,hide:true}],true),lineHighlighter:new LineHighlighter("code-2"),timer:new Timer,code:function(){var _code2=_asyncToGenerator(regeneratorRuntime.mark(function _callee4(){var proceed,tree;return regeneratorRuntime.wrap(function _callee4$(_context4){while(1)switch(_context4.prev=_context4.next){case 0:tree=new BinarySearchTree;tree.exampleFind=function(){var _ref2=_asyncToGenerator(regeneratorRuntime.mark(function _callee3(value,lineHighlighter,timer,visualTree,visualVariables){var current;return regeneratorRuntime.wrap(function _callee3$(_context3){while(1)switch(_context3.prev=
_context3.next){case 0:visualVariables.show("variable-find-value");visualVariables.setValue("variable-find-value",value);lineHighlighter.highlight(6);_context3.next=5;return timer.wait(500);case 5:proceed=_context3.sent;if(proceed){_context3.next=8;break}return _context3.abrupt("return");case 8:lineHighlighter.clear();if(this.root){_context3.next=12;break}visualVariables.hide("variable-find-value");return _context3.abrupt("return",false);case 12:current=this.root;visualTree.setPointerToNode("current",
this.root.value);lineHighlighter.highlight(9);_context3.next=17;return timer.wait(500);case 17:proceed=_context3.sent;if(proceed){_context3.next=20;break}return _context3.abrupt("return");case 20:lineHighlighter.clear();lineHighlighter.highlight(12);_context3.next=24;return timer.wait(500);case 24:proceed=_context3.sent;if(proceed){_context3.next=27;break}return _context3.abrupt("return");case 27:lineHighlighter.clear();case 28:if(!current){_context3.next=77;break}lineHighlighter.highlight(14);_context3.next=
32;return timer.wait(500);case 32:proceed=_context3.sent;if(proceed){_context3.next=35;break}return _context3.abrupt("return");case 35:lineHighlighter.clear();if(!(value===current.value)){_context3.next=40;break}visualTree.hidePointer("current");visualVariables.hide("variable-find-value");return _context3.abrupt("return",current);case 40:lineHighlighter.highlight(17);_context3.next=43;return timer.wait(500);case 43:proceed=_context3.sent;if(proceed){_context3.next=46;break}return _context3.abrupt("return");
case 46:lineHighlighter.clear();if(!(value>current.value)){_context3.next=59;break}current=current.right;visualTree.setPointerToNode("current",current.value);lineHighlighter.highlight(18);_context3.next=53;return timer.wait(500);case 53:proceed=_context3.sent;if(proceed){_context3.next=56;break}return _context3.abrupt("return");case 56:lineHighlighter.clear();_context3.next=68;break;case 59:current=current.left;visualTree.setPointerToNode("current",current.value);lineHighlighter.highlight(21);_context3.next=
64;return timer.wait(500);case 64:proceed=_context3.sent;if(proceed){_context3.next=67;break}return _context3.abrupt("return");case 67:lineHighlighter.clear();case 68:lineHighlighter.highlight(12);_context3.next=71;return timer.wait(500);case 71:proceed=_context3.sent;if(proceed){_context3.next=74;break}return _context3.abrupt("return");case 74:lineHighlighter.clear();_context3.next=28;break;case 77:lineHighlighter.highlight(25);_context3.next=80;return timer.wait(500);case 80:proceed=_context3.sent;
if(proceed){_context3.next=83;break}return _context3.abrupt("return");case 83:lineHighlighter.clear();visualTree.hidePointer("current");return _context3.abrupt("return",false);case 86:case "end":return _context3.stop()}},_callee3,this)}));return function(_x6,_x7,_x8,_x9,_x10){return _ref2.apply(this,arguments)}}();this.lineHighlighter.highlight(30);_context4.next=5;return this.timer.wait(500);case 5:proceed=_context4.sent;if(proceed){_context4.next=8;break}return _context4.abrupt("return");case 8:this.lineHighlighter.clear();
tree.insert(10).insert(5).insert(13).insert(11).insert(2).insert(16).insert(7).insert(3);this.visualTree.insert(10).insert(5).insert(13).insert(11).insert(2).insert(16).insert(7).insert(3);this.lineHighlighter.highlight(32);_context4.next=14;return this.timer.wait(500);case 14:proceed=_context4.sent;if(proceed){_context4.next=17;break}return _context4.abrupt("return");case 17:this.lineHighlighter.clear();this.lineHighlighter.highlight(35);_context4.next=21;return this.timer.wait(500);case 21:proceed=
_context4.sent;if(proceed){_context4.next=24;break}return _context4.abrupt("return");case 24:this.lineHighlighter.clear();_context4.next=27;return tree.exampleFind(11,this.lineHighlighter,this.timer,this.visualTree,this.visualVariables);case 27:this.visualTree.setPointerToNode("vyhledanaNode1",11);if(proceed){_context4.next=30;break}return _context4.abrupt("return");case 30:this.lineHighlighter.highlight(35);_context4.next=33;return this.timer.wait(500);case 33:proceed=_context4.sent;if(proceed){_context4.next=
36;break}return _context4.abrupt("return");case 36:this.lineHighlighter.clear();this.lineHighlighter.highlight(37);_context4.next=40;return this.timer.wait(500);case 40:proceed=_context4.sent;if(proceed){_context4.next=43;break}return _context4.abrupt("return");case 43:this.lineHighlighter.clear();_context4.next=46;return tree.exampleFind(3,this.lineHighlighter,this.timer,this.visualTree,this.visualVariables);case 46:this.visualTree.setPointerToNode("vyhledanaNode2",3);if(proceed){_context4.next=
49;break}return _context4.abrupt("return");case 49:this.lineHighlighter.highlight(37);_context4.next=52;return this.timer.wait(500);case 52:proceed=_context4.sent;if(proceed){_context4.next=55;break}return _context4.abrupt("return");case 55:this.lineHighlighter.clear();this.finish();case 57:case "end":return _context4.stop()}},_callee4,this)}));function code(){return _code2.apply(this,arguments)}return code}()}];initExamples(config);