function _createForOfIteratorHelper(o,allowArrayLike){var it=typeof Symbol!=="undefined"&&o[Symbol.iterator]||o["@@iterator"];if(!it){if(Array.isArray(o)||(it=_unsupportedIterableToArray(o))||allowArrayLike&&o&&typeof o.length==="number"){if(it)o=it;var i=0;var F=function F(){};return{s:F,n:function n(){if(i>=o.length)return{done:true};return{done:false,value:o[i++]}},e:function e(_e){throw _e;},f:F}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
}var normalCompletion=true,didErr=false,err;return{s:function s(){it=it.call(o)},n:function n(){var step=it.next();normalCompletion=step.done;return step},e:function e(_e2){didErr=true;err=_e2},f:function f(){try{if(!normalCompletion&&it["return"]!=null)it["return"]()}finally{if(didErr)throw err;}}}}
function _unsupportedIterableToArray(o,minLen){if(!o)return;if(typeof o==="string")return _arrayLikeToArray(o,minLen);var n=Object.prototype.toString.call(o).slice(8,-1);if(n==="Object"&&o.constructor)n=o.constructor.name;if(n==="Map"||n==="Set")return Array.from(o);if(n==="Arguments"||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n))return _arrayLikeToArray(o,minLen)}
function _arrayLikeToArray(arr,len){if(len==null||len>arr.length)len=arr.length;for(var i=0,arr2=new Array(len);i<len;i++)arr2[i]=arr[i];return arr2}function asyncGeneratorStep(gen,resolve,reject,_next,_throw,key,arg){try{var info=gen[key](arg);var value=info.value}catch(error){reject(error);return}if(info.done)resolve(value);else Promise.resolve(value).then(_next,_throw)}
function _asyncToGenerator(fn){return function(){var self=this,args=arguments;return new Promise(function(resolve,reject){var gen=fn.apply(self,args);function _next(value){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"next",value)}function _throw(err){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"throw",err)}_next(undefined)})}}
function _defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor)}}
function _createClass(Constructor,protoProps,staticProps){if(protoProps)_defineProperties(Constructor.prototype,protoProps);if(staticProps)_defineProperties(Constructor,staticProps);Object.defineProperty(Constructor,"prototype",{writable:false});return Constructor}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor))throw new TypeError("Cannot call a class as a function");}var Timer=InteractiveExample.Timer;var VisualDijkstraExplanation=InteractiveExample.VisualDijkstraExplanation;
var initExamples=InteractiveExample.initExamples;var VisualGraph=InteractiveExample.VisualGraph;var Console=InteractiveExample.Console;var VisualObjects=InteractiveExample.VisualObjects;var VisualObject=InteractiveExample.VisualObject;var VisualPriorityQueue=InteractiveExample.VisualPriorityQueue;var LineHighlighter=InteractiveExample.LineHighlighter;var Node=_createClass(function Node(value,priority){_classCallCheck(this,Node);this.value=value;this.priority=priority});
var PriorityQueue=function(){function PriorityQueue(){_classCallCheck(this,PriorityQueue);this.values=[];this.length=0}_createClass(PriorityQueue,[{key:"enqueue",value:function enqueue(value,priority){this.values.push(new Node(value,priority));this.length++;this.bubbleUp()}},{key:"bubbleUp",value:function bubbleUp(){var idx=this.values.length-1;while(idx>0){var parentIdx=Math.trunc((idx-1)/2);if(this.values[idx].priority>=this.values[parentIdx].priority)break;var parent=this.values[parentIdx];this.values[parentIdx]=
this.values[idx];this.values[idx]=parent;idx=parentIdx}}},{key:"dequeue",value:function dequeue(){var max=this.values[0];var end=this.values.pop();this.length--;if(this.values.length>0){this.values[0]=end;this.sinkDown()}return max}},{key:"sinkDown",value:function sinkDown(){var idx=0;var length=this.values.length;var element=this.values[0];while(true){var leftChildIdx=2*idx+1;var rightChildIdx=2*idx+2;var leftChild=void 0,rightChild=void 0;var swap=null;if(leftChildIdx<length){leftChild=this.values[leftChildIdx];
if(leftChild.priority<element.priority)swap=leftChildIdx}if(rightChildIdx<length){rightChild=this.values[rightChildIdx];if(swap===null&&rightChild.priority<element.priority||swap!==null&&rightChild.priority<leftChild.priority)swap=rightChildIdx}if(swap===null)break;this.values[idx]=this.values[swap];this.values[swap]=element;idx=swap}}}]);return PriorityQueue}();
var WeightedGraph=function(){function WeightedGraph(){_classCallCheck(this,WeightedGraph);this.adjacencyList={}}_createClass(WeightedGraph,[{key:"addVertex",value:function addVertex(vertex){if(!this.adjacencyList[vertex])this.adjacencyList[vertex]=[]}},{key:"addEdge",value:function addEdge(v1,v2,weight){if(!this.adjacencyList[v1]||!this.adjacencyList[v2])return;if(this.adjacencyList[v1].findIndex(function(v){return v.node===v2})===-1)this.adjacencyList[v1].push({node:v2,weight:weight});if(this.adjacencyList[v2].findIndex(function(v){return v.node===
v1})===-1)this.adjacencyList[v2].push({node:v1,weight:weight})}},{key:"removeEdge",value:function removeEdge(v1,v2){if(!this.adjacencyList[v1]||!this.adjacencyList[v2])return;var index=this.adjacencyList[v1].findIndex(function(v){return v.node===v2});if(index!==-1)this.adjacencyList[v1].splice(index,1);index=this.adjacencyList[v2].findIndex(function(v){return v.node===v1});if(index!==-1)this.adjacencyList[v2].splice(index,1)}},{key:"removeVertex",value:function removeVertex(vertex){while(this.adjacencyList[vertex].length){var adjacentVertex=
this.adjacencyList[vertex].pop();this.removeEdge(vertex,adjacentVertex.node)}delete this.adjacencyList[vertex]}}]);return WeightedGraph}();
var config=[{exampleId:1,timer:new Timer,visualDijkstraExplanation:new VisualDijkstraExplanation("dijkstra-explanation-graph","dijkstra-explanation-message","dijkstra-explanation-shortest-path-table-body",[{vertex:"A",elementId:"previous-vertex-1"},{vertex:"B",elementId:"previous-vertex-2"},{vertex:"C",elementId:"previous-vertex-3"},{vertex:"D",elementId:"previous-vertex-4"},{vertex:"E",elementId:"previous-vertex-5"},{vertex:"F",elementId:"previous-vertex-6"}],"dijkstra-explanation-visited-vertices"),
code:function(){var _code=_asyncToGenerator(regeneratorRuntime.mark(function _callee2(){var proceed,graph;return regeneratorRuntime.wrap(function _callee2$(_context2){while(1)switch(_context2.prev=_context2.next){case 0:_context2.next=2;return this.timer.wait(500);case 2:proceed=_context2.sent;if(proceed){_context2.next=5;break}return _context2.abrupt("return");case 5:graph=new WeightedGraph;graph.addVertex("A");graph.addVertex("B");graph.addVertex("E");graph.addVertex("F");graph.addVertex("D");graph.addVertex("C");
graph.addEdge("A","B",4);graph.addEdge("A","C",2);graph.addEdge("B","E",3);graph.addEdge("C","D",2);graph.addEdge("D","E",3);graph.addEdge("D","F",1);graph.addEdge("C","F",4);graph.addEdge("F","E",1);graph.exampleShortestPath=function(){var _ref=_asyncToGenerator(regeneratorRuntime.mark(function _callee(start,finish,timer,visualDijkstraExplanation){var nodes,distances,previous,path,smallest,vertex,vertexFForSecondTime,firstNeighbor,neighborIndex,_iterator,_step,neighbor,candidate,oldDistance;return regeneratorRuntime.wrap(function _callee$(_context){while(1)switch(_context.prev=
_context.next){case 0:nodes=new PriorityQueue;distances={};previous={};path=[];_context.t0=regeneratorRuntime.keys(this.adjacencyList);case 5:if((_context.t1=_context.t0()).done){_context.next=24;break}vertex=_context.t1.value;if(!(vertex===start)){_context.next=19;break}distances[vertex]=0;nodes.enqueue(vertex,0);visualDijkstraExplanation.setMessage("Za\u010dneme u vertexu A. V\u00edme \u017ee nejkrat\u0161\u00ed vzd\u00e1lenost z vertexu A do A, je 0, tak\u017ee jsme si to zapsali do tabulky s nejkrat\u0161\u00edmi vzd\u00e1lenostmi.");
visualDijkstraExplanation.changeShortestPath(vertex,0);_context.next=14;return timer.wait(500);case 14:proceed=_context.sent;if(proceed){_context.next=17;break}return _context.abrupt("return");case 17:_context.next=21;break;case 19:distances[vertex]=Infinity;nodes.enqueue(vertex,Infinity);case 21:previous[vertex]=null;_context.next=5;break;case 24:vertexFForSecondTime=false;case 25:if(!(nodes.length>0)){_context.next=126;break}smallest=nodes.dequeue().value;if(!(smallest==="F")){_context.next=33;
break}if(vertexFForSecondTime){_context.next=32;break}vertexFForSecondTime=true;_context.next=33;break;case 32:return _context.abrupt("continue",25);case 33:if(smallest==="A")visualDijkstraExplanation.setMessage("Pod\u00edv\u00e1me se na tabulku s nejkrat\u0161\u00edmi vzd\u00e1lenostmi. Vybereme si vertex s nejkrat\u0161\u00ed vzd\u00e1lenost\u00ed od vertexu A.");else visualDijkstraExplanation.setMessage("Pod\u00edv\u00e1me se na tabulku s nejkrat\u0161\u00edmi vzd\u00e1lenostmi. Vybereme si vertex s nejkrat\u0161\u00ed vzd\u00e1lenost\u00ed od vertexu A, kter\u00fd jsme je\u0161t\u011b nenav\u0161t\u00edvili (nebo jsme jej nav\u0161t\u00edvili, ale mezit\u00edm se u n\u011bj zm\u011bnila hodnota).");
_context.next=36;return timer.wait(500);case 36:proceed=_context.sent;if(proceed){_context.next=39;break}return _context.abrupt("return");case 39:visualDijkstraExplanation.setActiveVertex(smallest);if(smallest==="A")visualDijkstraExplanation.setMessage("V tabulce zat\u00edm m\u00e1me nejkrat\u0161\u00ed vzd\u00e1lenost jen pro vertex A, tak\u017ee jsme si jej vybrali.");else if(smallest!=="B")visualDijkstraExplanation.setMessage("Nejkrat\u0161\u00ed vzd\u00e1lenost od vertexu A m\u00e1 vertex ".concat(smallest,
", tak\u017ee jsme si jej vybrali."));else visualDijkstraExplanation.setMessage("Nejkrat\u0161\u00ed vzd\u00e1lenost od vertexu A m\u00e1 vertex B nebo D. Vybrali jsme si t\u0159eba B.");_context.next=43;return timer.wait(500);case 43:proceed=_context.sent;if(proceed){_context.next=46;break}return _context.abrupt("return");case 46:if(!(smallest===finish)){_context.next=62;break}while(previous[smallest]){path.push(smallest);smallest=previous[smallest]}visualDijkstraExplanation.setMessage("Proto\u017ee jsme si vybrali vertex, ke kter\u00e9mu jsme cht\u011bli z\u00edskat nejkrat\u0161\u00ed cestu, tak m\u00e1me hotovo.");
_context.next=51;return timer.wait(500);case 51:proceed=_context.sent;if(proceed){_context.next=54;break}return _context.abrupt("return");case 54:visualDijkstraExplanation.setMessage("Zjistili jsme, \u017ee nejkrat\u0161\u00ed cesta z vertexu A k vertexu E vede p\u0159es vertexy C, D a F. P\u0159edchoz\u00ed vertex vertexu E je F, p\u0159echoz\u00ed vertex vertexu F je D, p\u0159edchoz\u00ed vertex vertexu D je C a p\u0159echoz\u00ed vertex vertexu C je A.");_context.next=57;return timer.wait(500);
case 57:proceed=_context.sent;if(proceed){_context.next=60;break}return _context.abrupt("return");case 60:visualDijkstraExplanation.setMessage("Douf\u00e1m, \u017ee v\u00e1m tato vizu\u00e1ln\u00ed uk\u00e1zka pomohla Dijkstr\u016fv algoritmus pochopit. :)");return _context.abrupt("break",126);case 62:visualDijkstraExplanation.setMessage("Projdeme v\u0161echny vertexy, se kter\u00fdmi je vertex ".concat(smallest," propojen\u00fd."));_context.next=65;return timer.wait(500);case 65:proceed=_context.sent;
if(proceed){_context.next=68;break}return _context.abrupt("return");case 68:firstNeighbor=true;neighborIndex=0;_iterator=_createForOfIteratorHelper(this.adjacencyList[smallest]);_context.prev=71;_iterator.s();case 73:if((_step=_iterator.n()).done){_context.next=108;break}neighbor=_step.value;candidate=distances[smallest]+neighbor.weight;if(firstNeighbor)visualDijkstraExplanation.setMessage("Za\u010dneme t\u0159eba u vertexu ".concat(neighbor.node,". "));else if(this.adjacencyList[smallest].length===
2)visualDijkstraExplanation.setMessage("D\u00e1le se pod\u00edv\u00e1me je\u0161t\u011b na druh\u00fd vertex, se kter\u00fdm je vertex ".concat(smallest," propojen. Tak\u017ee na vertex ").concat(neighbor.node,"."));else if(neighborIndex===this.adjacencyList[smallest].length-1)visualDijkstraExplanation.setMessage("A je\u0161t\u011b se pod\u00edv\u00e1me na posledn\u00ed vertex, se kter\u00fdm je vertex ".concat(smallest," propojen. Tak\u017ee na vertex ").concat(neighbor.node,"."));else visualDijkstraExplanation.setMessage("Pod\u00edv\u00e1me se na dal\u0161\u00ed vertex, se kter\u00fdm je vertex ".concat(smallest,
" propojen. T\u0159eba na vertex ").concat(neighbor.node,"."));_context.next=79;return timer.wait(500);case 79:proceed=_context.sent;if(proceed){_context.next=82;break}return _context.abrupt("return");case 82:firstNeighbor=false;neighborIndex++;if(!(candidate<distances[neighbor.node])){_context.next=100;break}oldDistance=distances[neighbor.node];distances[neighbor.node]=candidate;previous[neighbor.node]=smallest;nodes.enqueue(neighbor.node,candidate);visualDijkstraExplanation.changeShortestPath(neighbor.node,
candidate);visualDijkstraExplanation.setPreviousVertex(neighbor.node,smallest);if(visualDijkstraExplanation.isVisited(neighbor.node))visualDijkstraExplanation.setAsUnvisited(neighbor.node);if(oldDistance===Infinity)if(smallest==="A")visualDijkstraExplanation.setMessage("Pro vertex ".concat(neighbor.node," v tabulce je\u0161t\u011b nem\u00e1me \u017e\u00e1dnou hodnotu. Vzd\u00e1lenost k vertexu ").concat(neighbor.node," od vertexu A je ").concat(candidate,", tak\u017ee jsme si to zapsali. Tak\u00e9 jsme si zapamatovali, \u017ee p\u0159edch\u00e1zej\u00edc\u00edm vertexem vertexu ").concat(neighbor.node,
" je p\u0159\u00edmo vertex A."));else visualDijkstraExplanation.setMessage("Pro vertex ".concat(neighbor.node," v tabulce je\u0161t\u011b nem\u00e1me \u017e\u00e1dnou hodnotu. P\u0159es vertex ").concat(smallest," je vzd\u00e1lenost k tomuto vertexu ").concat(candidate,", tak\u017ee jsme si to zapsali. Tak\u00e9 jsme si zapamatovali, \u017ee jsme se k tomuto vertexu dostali p\u0159es vertex ").concat(smallest,"."));else visualDijkstraExplanation.setMessage("Na vertex ".concat(neighbor.node," je cesta p\u0159es vertex ").concat(smallest,
" krat\u0161\u00ed, ne\u017e cesta, kterou jsme m\u011bli zaznamenanou. Tak\u017ee jsme vzd\u00e1lenost k tomuto vertexu p\u0159epsali z ").concat(oldDistance," na ").concat(candidate,". Tak\u00e9 jsme si zapamatovali, \u017ee nejkrat\u0161\u00ed cesta k vertexu ").concat(neighbor.node," vede p\u0159es vertex ").concat(smallest," (P\u0159edch\u00e1zej\u00edc\u00ed vertex vertexu ").concat(neighbor.node," je ").concat(smallest,")."));_context.next=95;return timer.wait(500);case 95:proceed=_context.sent;
if(proceed){_context.next=98;break}return _context.abrupt("return");case 98:_context.next=106;break;case 100:if(neighbor.node==="A")visualDijkstraExplanation.setMessage("Na vertex A nen\u00ed cesta p\u0159es vertex ".concat(smallest," krat\u0161\u00ed. Od vertexu A cesta za\u010d\u00edn\u00e1, vzd\u00e1lenost na vertex A je tedy 0, co\u017e je nejkrat\u0161\u00ed vzd\u00e1lenost."));else visualDijkstraExplanation.setMessage("Na vertex ".concat(neighbor.node," nen\u00ed cesta p\u0159es vertex ").concat(smallest,
" krat\u0161\u00ed. V tabulce jsme tedy hodnotu pro vertex ").concat(neighbor.node," nezm\u011bnili."));_context.next=103;return timer.wait(500);case 103:proceed=_context.sent;if(proceed){_context.next=106;break}return _context.abrupt("return");case 106:_context.next=73;break;case 108:_context.next=113;break;case 110:_context.prev=110;_context.t2=_context["catch"](71);_iterator.e(_context.t2);case 113:_context.prev=113;_iterator.f();return _context.finish(113);case 116:visualDijkstraExplanation.setAsVisited(smallest);
visualDijkstraExplanation.setMessage("Ozna\u010dili jsme si, \u017ee vertex ".concat(smallest," jsme ji\u017e nav\u0161t\u00edvili."));_context.next=120;return timer.wait(500);case 120:proceed=_context.sent;if(proceed){_context.next=123;break}return _context.abrupt("return");case 123:visualDijkstraExplanation.unsetActiveVertex();_context.next=25;break;case 126:return _context.abrupt("return",path.concat(smallest).reverse());case 127:case "end":return _context.stop()}},_callee,this,[[71,110,113,116]])}));
return function(_x,_x2,_x3,_x4){return _ref.apply(this,arguments)}}();_context2.next=23;return graph.exampleShortestPath("A","E",this.timer,this.visualDijkstraExplanation);case 23:this.finish();case 24:case "end":return _context2.stop()}},_callee2,this)}));function code(){return _code.apply(this,arguments)}return code}()},{exampleId:2,visualGraph:new VisualGraph("weighted-graph-1",["start","finish","vertex","smallest","neighbor"]),timer:new Timer,console:new Console("console-1"),visualObjects:new VisualObjects(new VisualObject("code-distances-object",
["code-distance-A","code-distance-B","code-distance-C","code-distance-D","code-distance-E","code-distance-F"]),new VisualObject("code-previous-object",["code-previous-vertex-A","code-previous-vertex-B","code-previous-vertex-C","code-previous-vertex-D","code-previous-vertex-E","code-previous-vertex-F"])),visualTree:new VisualPriorityQueue("priority-queue-1"),lineHighlighter:new LineHighlighter("code-1"),code:function(){var _code2=_asyncToGenerator(regeneratorRuntime.mark(function _callee4(){var proceed,
graph,cesta;return regeneratorRuntime.wrap(function _callee4$(_context4){while(1)switch(_context4.prev=_context4.next){case 0:graph=new WeightedGraph;graph.addVertex("A");graph.addVertex("B");graph.addVertex("E");graph.addVertex("F");graph.addVertex("D");graph.addVertex("C");graph.addEdge("A","B",4);graph.addEdge("A","C",2);graph.addEdge("B","E",3);graph.addEdge("C","D",2);graph.addEdge("D","E",3);graph.addEdge("D","F",1);graph.addEdge("C","F",4);graph.addEdge("F","E",1);graph.exampleShortestPath=
function(){var _ref2=_asyncToGenerator(regeneratorRuntime.mark(function _callee3(start,finish,lineHighlighter,timer,visualGraph,visualObjects,visualTree){var nodes,distances,previous,path,smallest,vertex,_iterator2,_step2,neighbor,candidate;return regeneratorRuntime.wrap(function _callee3$(_context3){while(1)switch(_context3.prev=_context3.next){case 0:visualGraph.setPointerToVertex("start",start);visualGraph.setPointerUp("start");visualGraph.setPointerToVertex("finish",finish);visualGraph.setPointerUp("finish");
nodes=new PriorityQueue;lineHighlighter.highlight(6);_context3.next=8;return timer.wait(500);case 8:proceed=_context3.sent;if(proceed){_context3.next=11;break}return _context3.abrupt("return");case 11:lineHighlighter.clear();distances={};visualObjects.get(0).show();lineHighlighter.highlight(8);_context3.next=17;return timer.wait(500);case 17:proceed=_context3.sent;if(proceed){_context3.next=20;break}return _context3.abrupt("return");case 20:lineHighlighter.clear();previous={};visualObjects.get(1).show();
lineHighlighter.highlight(10);_context3.next=26;return timer.wait(500);case 26:proceed=_context3.sent;if(proceed){_context3.next=29;break}return _context3.abrupt("return");case 29:lineHighlighter.clear();path=[];lineHighlighter.highlight(12);_context3.next=34;return timer.wait(500);case 34:proceed=_context3.sent;if(proceed){_context3.next=37;break}return _context3.abrupt("return");case 37:lineHighlighter.clear();lineHighlighter.highlight(14);_context3.next=41;return timer.wait(500);case 41:proceed=
_context3.sent;if(proceed){_context3.next=44;break}return _context3.abrupt("return");case 44:lineHighlighter.clear();_context3.t0=regeneratorRuntime.keys(this.adjacencyList);case 46:if((_context3.t1=_context3.t0()).done){_context3.next=116;break}vertex=_context3.t1.value;visualGraph.setPointerToVertex("vertex",vertex);if(vertex==="F")visualGraph.setPointerUp("vertex");lineHighlighter.highlight(17);_context3.next=53;return timer.wait(500);case 53:proceed=_context3.sent;if(proceed){_context3.next=56;
break}return _context3.abrupt("return");case 56:lineHighlighter.clear();lineHighlighter.highlight(18);_context3.next=60;return timer.wait(500);case 60:proceed=_context3.sent;if(proceed){_context3.next=63;break}return _context3.abrupt("return");case 63:lineHighlighter.clear();if(!(vertex===start)){_context3.next=85;break}distances[vertex]=0;visualObjects.get(0).setValue("code-distance-"+vertex,0);lineHighlighter.highlight(20);_context3.next=70;return timer.wait(500);case 70:proceed=_context3.sent;
if(proceed){_context3.next=73;break}return _context3.abrupt("return");case 73:lineHighlighter.clear();nodes.enqueue(vertex,0);visualTree.enqueue(vertex,0,false,true);lineHighlighter.highlight(22);_context3.next=79;return timer.wait(500);case 79:proceed=_context3.sent;if(proceed){_context3.next=82;break}return _context3.abrupt("return");case 82:lineHighlighter.clear();_context3.next=103;break;case 85:distances[vertex]=Infinity;visualObjects.get(0).setValue("code-distance-"+vertex,Infinity);lineHighlighter.highlight(25);
_context3.next=90;return timer.wait(500);case 90:proceed=_context3.sent;if(proceed){_context3.next=93;break}return _context3.abrupt("return");case 93:lineHighlighter.clear();nodes.enqueue(vertex,Infinity);visualTree.enqueue(vertex,Infinity,false,true);lineHighlighter.highlight(27);_context3.next=99;return timer.wait(500);case 99:proceed=_context3.sent;if(proceed){_context3.next=102;break}return _context3.abrupt("return");case 102:lineHighlighter.clear();case 103:previous[vertex]=null;visualObjects.get(1).setValue("code-previous-vertex-"+
vertex,"null");lineHighlighter.highlight(30);_context3.next=108;return timer.wait(500);case 108:proceed=_context3.sent;if(proceed){_context3.next=111;break}return _context3.abrupt("return");case 111:lineHighlighter.clear();visualGraph.hidePointer("vertex");visualGraph.setPointerDown("vertex");_context3.next=46;break;case 116:lineHighlighter.highlight(17);_context3.next=119;return timer.wait(500);case 119:proceed=_context3.sent;if(proceed){_context3.next=122;break}return _context3.abrupt("return");
case 122:lineHighlighter.clear();lineHighlighter.highlight(34);_context3.next=126;return timer.wait(500);case 126:proceed=_context3.sent;if(proceed){_context3.next=129;break}return _context3.abrupt("return");case 129:lineHighlighter.clear();case 130:if(!(nodes.length>0)){_context3.next=281;break}smallest=nodes.dequeue().value;visualTree.dequeue(true);visualGraph.setPointerToVertex("smallest",smallest);if(smallest==="F")visualGraph.setPointerUp("smallest");lineHighlighter.highlight(36);_context3.next=
138;return timer.wait(500);case 138:proceed=_context3.sent;if(proceed){_context3.next=141;break}return _context3.abrupt("return");case 141:lineHighlighter.clear();lineHighlighter.highlight(39);_context3.next=145;return timer.wait(500);case 145:proceed=_context3.sent;if(proceed){_context3.next=148;break}return _context3.abrupt("return");case 148:lineHighlighter.clear();if(!(smallest===finish)){_context3.next=194;break}lineHighlighter.highlight(41);_context3.next=153;return timer.wait(500);case 153:proceed=
_context3.sent;if(proceed){_context3.next=156;break}return _context3.abrupt("return");case 156:lineHighlighter.clear();case 157:if(!previous[smallest]){_context3.next=185;break}path.push(smallest);lineHighlighter.highlight(42);_context3.next=162;return timer.wait(500);case 162:proceed=_context3.sent;if(proceed){_context3.next=165;break}return _context3.abrupt("return");case 165:lineHighlighter.clear();smallest=previous[smallest];visualGraph.setPointerToVertex("smallest",smallest);if(smallest==="F")visualGraph.setPointerUp("smallest");
else visualGraph.setPointerDown("smallest");lineHighlighter.highlight(43);_context3.next=172;return timer.wait(500);case 172:proceed=_context3.sent;if(proceed){_context3.next=175;break}return _context3.abrupt("return");case 175:lineHighlighter.clear();lineHighlighter.highlight(41);_context3.next=179;return timer.wait(500);case 179:proceed=_context3.sent;if(proceed){_context3.next=182;break}return _context3.abrupt("return");case 182:lineHighlighter.clear();_context3.next=157;break;case 185:lineHighlighter.highlight(46);
_context3.next=188;return timer.wait(500);case 188:proceed=_context3.sent;if(proceed){_context3.next=191;break}return _context3.abrupt("return");case 191:lineHighlighter.clear();visualGraph.hidePointer("smallest");return _context3.abrupt("break",281);case 194:_iterator2=_createForOfIteratorHelper(this.adjacencyList[smallest]);_context3.prev=195;_iterator2.s();case 197:if((_step2=_iterator2.n()).done){_context3.next=255;break}neighbor=_step2.value;visualGraph.setPointerToVertex("neighbor",neighbor.node);
if(neighbor.node==="F")visualGraph.setPointerUp("neighbor");lineHighlighter.highlight(50);_context3.next=204;return timer.wait(500);case 204:proceed=_context3.sent;if(proceed){_context3.next=207;break}return _context3.abrupt("return");case 207:lineHighlighter.clear();candidate=distances[smallest]+neighbor.weight;lineHighlighter.highlight(52);_context3.next=212;return timer.wait(500);case 212:proceed=_context3.sent;if(proceed){_context3.next=215;break}return _context3.abrupt("return");case 215:lineHighlighter.clear();
lineHighlighter.highlight(55);_context3.next=219;return timer.wait(500);case 219:proceed=_context3.sent;if(proceed){_context3.next=222;break}return _context3.abrupt("return");case 222:lineHighlighter.clear();if(!(candidate<distances[neighbor.node])){_context3.next=251;break}distances[neighbor.node]=candidate;visualObjects.get(0).setValue("code-distance-"+neighbor.node,candidate);lineHighlighter.highlight(57);_context3.next=229;return timer.wait(500);case 229:proceed=_context3.sent;if(proceed){_context3.next=
232;break}return _context3.abrupt("return");case 232:lineHighlighter.clear();previous[neighbor.node]=smallest;visualObjects.get(1).setValue("code-previous-vertex-"+neighbor.node,smallest);lineHighlighter.highlight(59);_context3.next=238;return timer.wait(500);case 238:proceed=_context3.sent;if(proceed){_context3.next=241;break}return _context3.abrupt("return");case 241:lineHighlighter.clear();nodes.enqueue(neighbor.node,candidate);visualTree.enqueue(neighbor.node,candidate,false,true);lineHighlighter.highlight(61);
_context3.next=247;return timer.wait(500);case 247:proceed=_context3.sent;if(proceed){_context3.next=250;break}return _context3.abrupt("return");case 250:lineHighlighter.clear();case 251:visualGraph.hidePointer("neighbor");visualGraph.setPointerDown("neighbor");case 253:_context3.next=197;break;case 255:_context3.next=260;break;case 257:_context3.prev=257;_context3.t2=_context3["catch"](195);_iterator2.e(_context3.t2);case 260:_context3.prev=260;_iterator2.f();return _context3.finish(260);case 263:lineHighlighter.highlight(50);
_context3.next=266;return timer.wait(500);case 266:proceed=_context3.sent;if(proceed){_context3.next=269;break}return _context3.abrupt("return");case 269:lineHighlighter.clear();visualGraph.hidePointer("smallest");visualGraph.setPointerDown("smallest");lineHighlighter.highlight(34);_context3.next=275;return timer.wait(500);case 275:proceed=_context3.sent;if(proceed){_context3.next=278;break}return _context3.abrupt("return");case 278:lineHighlighter.clear();_context3.next=130;break;case 281:lineHighlighter.highlight(66);
_context3.next=284;return timer.wait(500);case 284:proceed=_context3.sent;if(proceed){_context3.next=287;break}return _context3.abrupt("return");case 287:lineHighlighter.clear();visualGraph.hidePointer("start");visualGraph.hidePointer("finish");return _context3.abrupt("return",path.concat(smallest).reverse());case 291:case "end":return _context3.stop()}},_callee3,this,[[195,257,260,263]])}));return function(_x5,_x6,_x7,_x8,_x9,_x10,_x11){return _ref2.apply(this,arguments)}}();this.lineHighlighter.highlight(71);
_context4.next=19;return this.timer.wait(500);case 19:proceed=_context4.sent;if(proceed){_context4.next=22;break}return _context4.abrupt("return");case 22:this.lineHighlighter.clear();this.visualGraph.addVertex("A",140,0);this.visualGraph.addVertex("B",300,30);this.visualGraph.addVertex("E",430,100);this.lineHighlighter.highlight(72);_context4.next=29;return this.timer.wait(500);case 29:proceed=_context4.sent;if(proceed){_context4.next=32;break}return _context4.abrupt("return");case 32:this.lineHighlighter.clear();
this.visualGraph.addVertex("F",260,150);this.visualGraph.addVertex("D",200,60);this.visualGraph.addVertex("C",0,85);this.lineHighlighter.highlight(73);_context4.next=39;return this.timer.wait(500);case 39:proceed=_context4.sent;if(proceed){_context4.next=42;break}return _context4.abrupt("return");case 42:this.lineHighlighter.clear();this.visualGraph.addEdge("A","B",4);this.visualGraph.addEdge("A","C",2);this.visualGraph.addEdge("B","E",3);this.lineHighlighter.highlight(74);_context4.next=49;return this.timer.wait(500);
case 49:proceed=_context4.sent;if(proceed){_context4.next=52;break}return _context4.abrupt("return");case 52:this.lineHighlighter.clear();this.visualGraph.addEdge("C","D",2);this.visualGraph.addEdge("D","E",3);this.visualGraph.addEdge("D","F",1);this.lineHighlighter.highlight(75);_context4.next=59;return this.timer.wait(500);case 59:proceed=_context4.sent;if(proceed){_context4.next=62;break}return _context4.abrupt("return");case 62:this.lineHighlighter.clear();this.visualGraph.addEdge("C","F",4);
this.visualGraph.addEdge("F","E",1);this.lineHighlighter.highlight(76);_context4.next=68;return this.timer.wait(500);case 68:proceed=_context4.sent;if(proceed){_context4.next=71;break}return _context4.abrupt("return");case 71:this.lineHighlighter.clear();this.lineHighlighter.highlight(79);_context4.next=75;return this.timer.wait(500);case 75:proceed=_context4.sent;if(proceed){_context4.next=78;break}return _context4.abrupt("return");case 78:this.lineHighlighter.clear();_context4.next=81;return graph.exampleShortestPath("A",
"E",this.lineHighlighter,this.timer,this.visualGraph,this.visualObjects,this.visualTree);case 81:cesta=_context4.sent;if(proceed){_context4.next=84;break}return _context4.abrupt("return");case 84:this.lineHighlighter.highlight(79);_context4.next=87;return this.timer.wait(500);case 87:proceed=_context4.sent;if(proceed){_context4.next=90;break}return _context4.abrupt("return");case 90:this.lineHighlighter.clear();this.console.log("Nejkrat\u0161\u00ed cesta z vertexu A k vertexu E je:");this.lineHighlighter.highlight(80);
_context4.next=95;return this.timer.wait(500);case 95:proceed=_context4.sent;if(proceed){_context4.next=98;break}return _context4.abrupt("return");case 98:this.lineHighlighter.clear();this.console.log("["+cesta+"]");this.lineHighlighter.highlight(81);_context4.next=103;return this.timer.wait(500);case 103:proceed=_context4.sent;if(proceed){_context4.next=106;break}return _context4.abrupt("return");case 106:this.lineHighlighter.clear();this.finish();case 108:case "end":return _context4.stop()}},_callee4,
this)}));function code(){return _code2.apply(this,arguments)}return code}()}];initExamples(config);