function asyncGeneratorStep(gen,resolve,reject,_next,_throw,key,arg){try{var info=gen[key](arg);var value=info.value}catch(error){reject(error);return}if(info.done)resolve(value);else Promise.resolve(value).then(_next,_throw)}
function _asyncToGenerator(fn){return function(){var self=this,args=arguments;return new Promise(function(resolve,reject){var gen=fn.apply(self,args);function _next(value){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"next",value)}function _throw(err){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"throw",err)}_next(undefined)})}}var LineHighlighter=InteractiveExample.LineHighlighter;var Timer=InteractiveExample.Timer;var initExamples=InteractiveExample.initExamples;var Console=InteractiveExample.Console;
var CalculationStructure=InteractiveExample.CalculationStructure;var VisualArray=InteractiveExample.VisualArray;
var config=[{exampleId:1,lineHighlighter:new LineHighlighter("code-1"),timer:new Timer,console:new Console("console-1"),calculationStructure:new CalculationStructure("calculation-structure-1"),code:function(){var _code=_asyncToGenerator(regeneratorRuntime.mark(function _callee2(){var _this=this;var proceed,fib,id,vysledek;return regeneratorRuntime.wrap(function _callee2$(_context2){while(1)switch(_context2.prev=_context2.next){case 0:fib=function(){var _ref=_asyncToGenerator(regeneratorRuntime.mark(function _callee(n,
parentId,spaceMultiplier){var id,num1,num2;return regeneratorRuntime.wrap(function _callee$(_context){while(1)switch(_context.prev=_context.next){case 0:_this.lineHighlighter.highlight(2);_context.next=3;return _this.timer.wait(500);case 3:proceed=_context.sent;if(proceed){_context.next=6;break}return _context.abrupt("return");case 6:_this.lineHighlighter.clear();if(!(n===1)){_context.next=9;break}return _context.abrupt("return",0);case 9:_this.lineHighlighter.highlight(4);_context.next=12;return _this.timer.wait(500);
case 12:proceed=_context.sent;if(proceed){_context.next=15;break}return _context.abrupt("return");case 15:_this.lineHighlighter.clear();if(!(n<=3)){_context.next=18;break}return _context.abrupt("return",1);case 18:_this.lineHighlighter.highlight(7);_context.next=21;return _this.timer.wait(500);case 21:proceed=_context.sent;if(proceed){_context.next=24;break}return _context.abrupt("return");case 24:_this.lineHighlighter.clear();id=_this.calculationStructure.pushItem("fib(".concat(n-1,")"),parentId,
true,spaceMultiplier);_context.next=28;return fib(n-1,id,spaceMultiplier-1);case 28:num1=_context.sent;if(proceed){_context.next=31;break}return _context.abrupt("return");case 31:_this.calculationStructure.setText(num1,id);_this.lineHighlighter.highlight(7);_context.next=35;return _this.timer.wait(500);case 35:proceed=_context.sent;if(proceed){_context.next=38;break}return _context.abrupt("return");case 38:_this.lineHighlighter.clear();id=_this.calculationStructure.pushItem("fib(".concat(n-2,")"),
parentId,false,spaceMultiplier);_this.calculationStructure.addOperationSign("+",parentId);_context.next=43;return fib(n-2,id,spaceMultiplier-1);case 43:num2=_context.sent;if(proceed){_context.next=46;break}return _context.abrupt("return");case 46:_this.calculationStructure.setText(num2,id);_this.lineHighlighter.highlight(7);_context.next=50;return _this.timer.wait(500);case 50:proceed=_context.sent;if(proceed){_context.next=53;break}return _context.abrupt("return");case 53:_this.lineHighlighter.clear();
return _context.abrupt("return",num1+num2);case 55:case "end":return _context.stop()}},_callee)}));return function fib(_x,_x2,_x3){return _ref.apply(this,arguments)}}();this.lineHighlighter.highlight(10);_context2.next=4;return this.timer.wait(500);case 4:proceed=_context2.sent;if(proceed){_context2.next=7;break}return _context2.abrupt("return");case 7:this.lineHighlighter.clear();id=this.calculationStructure.pushItem("fib(6)");_context2.next=11;return fib(6,id,3);case 11:vysledek=_context2.sent;
if(proceed){_context2.next=14;break}return _context2.abrupt("return");case 14:this.calculationStructure.setText(vysledek,id);this.lineHighlighter.highlight(10);_context2.next=18;return this.timer.wait(500);case 18:proceed=_context2.sent;if(proceed){_context2.next=21;break}return _context2.abrupt("return");case 21:this.lineHighlighter.clear();this.console.log("\u0160est\u00e9 \u010d\u00edslo ve Fibonacciho posloupnosti je: "+vysledek);this.lineHighlighter.highlight(11);_context2.next=26;return this.timer.wait(500);
case 26:proceed=_context2.sent;if(proceed){_context2.next=29;break}return _context2.abrupt("return");case 29:this.lineHighlighter.clear();this.finish();case 31:case "end":return _context2.stop()}},_callee2,this)}));function code(){return _code.apply(this,arguments)}return code}()},{exampleId:2,lineHighlighter:new LineHighlighter("code-2"),timer:new Timer,console:new Console("console-2"),calculationStructure:new CalculationStructure("calculation-structure-2"),visualArray:new VisualArray("visual-array-1",
7),code:function(){var _code2=_asyncToGenerator(regeneratorRuntime.mark(function _callee4(){var _this2=this;var proceed,fib,id,vysledek;return regeneratorRuntime.wrap(function _callee4$(_context4){while(1)switch(_context4.prev=_context4.next){case 0:fib=function(){var _ref2=_asyncToGenerator(regeneratorRuntime.mark(function _callee3(n){var memo,parentId,spaceMultiplier,id,num1,num2,result,i,_args3=arguments;return regeneratorRuntime.wrap(function _callee3$(_context3){while(1)switch(_context3.prev=
_context3.next){case 0:memo=_args3.length>1&&_args3[1]!==undefined?_args3[1]:[];parentId=_args3.length>2?_args3[2]:undefined;spaceMultiplier=_args3.length>3?_args3[3]:undefined;_this2.lineHighlighter.highlight(3);_context3.next=6;return _this2.timer.wait(500);case 6:proceed=_context3.sent;if(proceed){_context3.next=9;break}return _context3.abrupt("return");case 9:_this2.lineHighlighter.clear();if(!(memo[n]!==undefined)){_context3.next=12;break}return _context3.abrupt("return",memo[n]);case 12:_this2.lineHighlighter.highlight(4);
_context3.next=15;return _this2.timer.wait(500);case 15:proceed=_context3.sent;if(proceed){_context3.next=18;break}return _context3.abrupt("return");case 18:_this2.lineHighlighter.clear();if(!(n===1)){_context3.next=21;break}return _context3.abrupt("return",0);case 21:_this2.lineHighlighter.highlight(5);_context3.next=24;return _this2.timer.wait(500);case 24:proceed=_context3.sent;if(proceed){_context3.next=27;break}return _context3.abrupt("return");case 27:_this2.lineHighlighter.clear();if(!(n<=
3)){_context3.next=30;break}return _context3.abrupt("return",1);case 30:_this2.lineHighlighter.highlight(6);_context3.next=33;return _this2.timer.wait(500);case 33:proceed=_context3.sent;if(proceed){_context3.next=36;break}return _context3.abrupt("return");case 36:_this2.lineHighlighter.clear();id=_this2.calculationStructure.pushItem("fib(".concat(n-1,")"),parentId,true,spaceMultiplier);_context3.next=40;return fib(n-1,memo,id,spaceMultiplier-1);case 40:num1=_context3.sent;if(proceed){_context3.next=
43;break}return _context3.abrupt("return");case 43:_this2.calculationStructure.setText(num1,id);_this2.lineHighlighter.highlight(6);_context3.next=47;return _this2.timer.wait(500);case 47:proceed=_context3.sent;if(proceed){_context3.next=50;break}return _context3.abrupt("return");case 50:_this2.lineHighlighter.clear();id=_this2.calculationStructure.pushItem("fib(".concat(n-2,")"),parentId,false,spaceMultiplier);_this2.calculationStructure.addOperationSign("+",parentId);_context3.next=55;return fib(n-
2,memo,id,spaceMultiplier-1);case 55:num2=_context3.sent;if(proceed){_context3.next=58;break}return _context3.abrupt("return");case 58:_this2.calculationStructure.setText(num2,id);_this2.lineHighlighter.highlight(6);_context3.next=62;return _this2.timer.wait(500);case 62:proceed=_context3.sent;if(proceed){_context3.next=65;break}return _context3.abrupt("return");case 65:_this2.lineHighlighter.clear();result=num1+num2;memo[n]=result;if(n===4)for(i=0;i<4;i++)_this2.visualArray.pushItem("&nbsp;");_this2.visualArray.pushItem(result);
_this2.lineHighlighter.highlight(8);_context3.next=73;return _this2.timer.wait(500);case 73:proceed=_context3.sent;if(proceed){_context3.next=76;break}return _context3.abrupt("return");case 76:_this2.lineHighlighter.clear();_this2.lineHighlighter.highlight(9);_context3.next=80;return _this2.timer.wait(500);case 80:proceed=_context3.sent;if(proceed){_context3.next=83;break}return _context3.abrupt("return");case 83:_this2.lineHighlighter.clear();return _context3.abrupt("return",result);case 85:case "end":return _context3.stop()}},
_callee3)}));return function fib(_x4){return _ref2.apply(this,arguments)}}();this.lineHighlighter.highlight(12);_context4.next=4;return this.timer.wait(500);case 4:proceed=_context4.sent;if(proceed){_context4.next=7;break}return _context4.abrupt("return");case 7:this.lineHighlighter.clear();id=this.calculationStructure.pushItem("fib(6)");_context4.next=11;return fib(6,[],id,3);case 11:vysledek=_context4.sent;if(proceed){_context4.next=14;break}return _context4.abrupt("return");case 14:this.calculationStructure.setText(vysledek,
id);this.lineHighlighter.highlight(12);_context4.next=18;return this.timer.wait(500);case 18:proceed=_context4.sent;if(proceed){_context4.next=21;break}return _context4.abrupt("return");case 21:this.lineHighlighter.clear();this.console.log("\u0160est\u00e9 \u010d\u00edslo ve Fibonacciho posloupnosti je: "+vysledek);this.lineHighlighter.highlight(13);_context4.next=26;return this.timer.wait(500);case 26:proceed=_context4.sent;if(proceed){_context4.next=29;break}return _context4.abrupt("return");case 29:this.lineHighlighter.clear();
this.finish();case 31:case "end":return _context4.stop()}},_callee4,this)}));function code(){return _code2.apply(this,arguments)}return code}()},{exampleId:3,lineHighlighter:new LineHighlighter("code-3"),timer:new Timer,console:new Console("console-3"),visualArray:new VisualArray("visual-array-2",6),code:function(){var _code3=_asyncToGenerator(regeneratorRuntime.mark(function _callee6(){var _this3=this;var proceed,fib,vysledek;return regeneratorRuntime.wrap(function _callee6$(_context6){while(1)switch(_context6.prev=
_context6.next){case 0:fib=function(){var _ref3=_asyncToGenerator(regeneratorRuntime.mark(function _callee5(n){var fibNums,i;return regeneratorRuntime.wrap(function _callee5$(_context5){while(1)switch(_context5.prev=_context5.next){case 0:fibNums=[0,1,1];_this3.visualArray.pushItem(0);_this3.visualArray.pushItem(1);_this3.visualArray.pushItem(1);_this3.lineHighlighter.highlight(2);_context5.next=7;return _this3.timer.wait(500);case 7:proceed=_context5.sent;if(proceed){_context5.next=10;break}return _context5.abrupt("return");
case 10:_this3.lineHighlighter.clear();n--;_this3.lineHighlighter.highlight(4);_context5.next=15;return _this3.timer.wait(500);case 15:proceed=_context5.sent;if(proceed){_context5.next=18;break}return _context5.abrupt("return");case 18:_this3.lineHighlighter.clear();_this3.lineHighlighter.highlight(6);_context5.next=22;return _this3.timer.wait(500);case 22:proceed=_context5.sent;if(proceed){_context5.next=25;break}return _context5.abrupt("return");case 25:_this3.lineHighlighter.clear();i=3;case 27:if(!(i<=
n)){_context5.next=47;break}fibNums[i]=fibNums[i-1]+fibNums[i-2];_this3.visualArray.pushItem(fibNums[i]);_this3.lineHighlighter.highlight(8);_context5.next=33;return _this3.timer.wait(500);case 33:proceed=_context5.sent;if(proceed){_context5.next=36;break}return _context5.abrupt("return");case 36:_this3.lineHighlighter.clear();_this3.lineHighlighter.highlight(6);_context5.next=40;return _this3.timer.wait(500);case 40:proceed=_context5.sent;if(proceed){_context5.next=43;break}return _context5.abrupt("return");
case 43:_this3.lineHighlighter.clear();case 44:i++;_context5.next=27;break;case 47:_this3.lineHighlighter.highlight(11);_context5.next=50;return _this3.timer.wait(500);case 50:proceed=_context5.sent;if(proceed){_context5.next=53;break}return _context5.abrupt("return");case 53:_this3.lineHighlighter.clear();return _context5.abrupt("return",fibNums[n]);case 55:case "end":return _context5.stop()}},_callee5)}));return function fib(_x5){return _ref3.apply(this,arguments)}}();this.lineHighlighter.highlight(14);
_context6.next=4;return this.timer.wait(500);case 4:proceed=_context6.sent;if(proceed){_context6.next=7;break}return _context6.abrupt("return");case 7:this.lineHighlighter.clear();_context6.next=10;return fib(6);case 10:vysledek=_context6.sent;if(proceed){_context6.next=13;break}return _context6.abrupt("return");case 13:this.lineHighlighter.highlight(14);_context6.next=16;return this.timer.wait(500);case 16:proceed=_context6.sent;if(proceed){_context6.next=19;break}return _context6.abrupt("return");
case 19:this.lineHighlighter.clear();this.console.log("\u0160est\u00e9 \u010d\u00edslo ve Fibonacciho posloupnosti je: "+vysledek);this.lineHighlighter.highlight(15);_context6.next=24;return this.timer.wait(500);case 24:proceed=_context6.sent;if(proceed){_context6.next=27;break}return _context6.abrupt("return");case 27:this.lineHighlighter.clear();this.finish();case 29:case "end":return _context6.stop()}},_callee6,this)}));function code(){return _code3.apply(this,arguments)}return code}()}];initExamples(config);