function _createForOfIteratorHelper(o,allowArrayLike){var it=typeof Symbol!=="undefined"&&o[Symbol.iterator]||o["@@iterator"];if(!it){if(Array.isArray(o)||(it=_unsupportedIterableToArray(o))||allowArrayLike&&o&&typeof o.length==="number"){if(it)o=it;var i=0;var F=function F(){};return{s:F,n:function n(){if(i>=o.length)return{done:true};return{done:false,value:o[i++]}},e:function e(_e){throw _e;},f:F}}throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
}var normalCompletion=true,didErr=false,err;return{s:function s(){it=it.call(o)},n:function n(){var step=it.next();normalCompletion=step.done;return step},e:function e(_e2){didErr=true;err=_e2},f:function f(){try{if(!normalCompletion&&it["return"]!=null)it["return"]()}finally{if(didErr)throw err;}}}}
function _unsupportedIterableToArray(o,minLen){if(!o)return;if(typeof o==="string")return _arrayLikeToArray(o,minLen);var n=Object.prototype.toString.call(o).slice(8,-1);if(n==="Object"&&o.constructor)n=o.constructor.name;if(n==="Map"||n==="Set")return Array.from(o);if(n==="Arguments"||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(n))return _arrayLikeToArray(o,minLen)}
function _arrayLikeToArray(arr,len){if(len==null||len>arr.length)len=arr.length;for(var i=0,arr2=new Array(len);i<len;i++)arr2[i]=arr[i];return arr2}function asyncGeneratorStep(gen,resolve,reject,_next,_throw,key,arg){try{var info=gen[key](arg);var value=info.value}catch(error){reject(error);return}if(info.done)resolve(value);else Promise.resolve(value).then(_next,_throw)}
function _asyncToGenerator(fn){return function(){var self=this,args=arguments;return new Promise(function(resolve,reject){var gen=fn.apply(self,args);function _next(value){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"next",value)}function _throw(err){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"throw",err)}_next(undefined)})}}
function _defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor)}}
function _createClass(Constructor,protoProps,staticProps){if(protoProps)_defineProperties(Constructor.prototype,protoProps);if(staticProps)_defineProperties(Constructor,staticProps);Object.defineProperty(Constructor,"prototype",{writable:false});return Constructor}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor))throw new TypeError("Cannot call a class as a function");}var LineHighlighter=InteractiveExample.LineHighlighter;var Timer=InteractiveExample.Timer;
var initExamples=InteractiveExample.initExamples;var VisualGraph=InteractiveExample.VisualGraph;var VisualArray=InteractiveExample.VisualArray;var VisualLinkedList=InteractiveExample.VisualLinkedList;var Console=InteractiveExample.Console;var CallStack=InteractiveExample.CallStack;var Stack=InteractiveExample.Stack;var Node=_createClass(function Node(value){_classCallCheck(this,Node);this.value=value;this.next=null});
var Queue=function(){function Queue(){_classCallCheck(this,Queue);this.first=null;this.last=null;this.size=0}_createClass(Queue,[{key:"enqueue",value:function enqueue(value){var newNode=new Node(value);if(!this.first){this.first=newNode;this.last=newNode}else{this.last.next=newNode;this.last=newNode}return++this.size}},{key:"dequeue",value:function dequeue(){if(!this.first)return null;var value=this.first.value;if(this.first===this.last)this.last=null;this.first=this.first.next;this.size--;return value}}]);
return Queue}();
var Graph=function(){function Graph(){_classCallCheck(this,Graph);this.adjacencyList={}}_createClass(Graph,[{key:"addVertex",value:function addVertex(vertex){if(!this.adjacencyList[vertex])this.adjacencyList[vertex]=[]}},{key:"addEdge",value:function addEdge(v1,v2){if(!this.adjacencyList[v1]||!this.adjacencyList[v2])return;if(!this.adjacencyList[v1].includes(v2))this.adjacencyList[v1].push(v2);if(!this.adjacencyList[v2].includes(v1))this.adjacencyList[v2].push(v1)}},{key:"removeEdge",value:function removeEdge(v1,
v2){if(!this.adjacencyList[v1]||!this.adjacencyList[v2])return;var index=this.adjacencyList[v1].findIndex(function(val){return val===v2});if(index!==-1)this.adjacencyList[v1].splice(index,1);index=this.adjacencyList[v2].findIndex(function(val){return val===v1});if(index!==-1)this.adjacencyList[v2].splice(index,1)}}]);return Graph}();
var config=[{exampleId:1,lineHighlighter:new LineHighlighter("code-1"),visualGraph:new VisualGraph("graph-1",["startVertex","vertex","adjacentVertex"]),visualArray:new VisualArray("visual-array-1",9),timer:new Timer,console:new Console("console-1"),callStack:new CallStack("call-stack-1"),code:function(){var _code=_asyncToGenerator(regeneratorRuntime.mark(function _callee3(){var proceed,graph,vysledek;return regeneratorRuntime.wrap(function _callee3$(_context3){while(1)switch(_context3.prev=_context3.next){case 0:graph=
new Graph;graph.exampleDFRecursive=function(){var _ref=_asyncToGenerator(regeneratorRuntime.mark(function _callee2(startVertex,lineHighlighter,timer,visualGraph,visualArray,callStack){var _this=this;var result,visited,df;return regeneratorRuntime.wrap(function _callee2$(_context2){while(1)switch(_context2.prev=_context2.next){case 0:callStack.push("DFRecursive");visualGraph.setPointerToVertex("startVertex",startVertex);visualGraph.setPointerUp("startVertex");result=[];lineHighlighter.highlight(6);
_context2.next=7;return timer.wait(500);case 7:proceed=_context2.sent;if(proceed){_context2.next=10;break}return _context2.abrupt("return");case 10:lineHighlighter.clear();visited={};lineHighlighter.highlight(8);_context2.next=15;return timer.wait(500);case 15:proceed=_context2.sent;if(proceed){_context2.next=18;break}return _context2.abrupt("return");case 18:lineHighlighter.clear();lineHighlighter.highlight(11);_context2.next=22;return timer.wait(500);case 22:proceed=_context2.sent;if(proceed){_context2.next=
25;break}return _context2.abrupt("return");case 25:lineHighlighter.clear();df=function(){var _ref2=_asyncToGenerator(regeneratorRuntime.mark(function _callee(vertex){var firstIteration,_iterator,_step,adjacentVertex;return regeneratorRuntime.wrap(function _callee$(_context){while(1)switch(_context.prev=_context.next){case 0:callStack.push("df");visualGraph.setPointerToVertex("vertex",vertex);if(vertex==="G"||vertex==="F"||vertex==="E"||vertex==="B")visualGraph.setPointerUp("vertex");else visualGraph.setPointerDown("vertex");
visualGraph.hidePointer("adjacentVertex");lineHighlighter.highlight(13);_context.next=7;return timer.wait(500);case 7:proceed=_context.sent;if(proceed){_context.next=10;break}return _context.abrupt("return");case 10:lineHighlighter.clear();if(_this.adjacencyList[vertex]){_context.next=13;break}return _context.abrupt("return");case 13:visited[vertex]=true;visualGraph.setVertexAsVisited(vertex);lineHighlighter.highlight(16);_context.next=18;return timer.wait(500);case 18:proceed=_context.sent;if(proceed){_context.next=
21;break}return _context.abrupt("return");case 21:lineHighlighter.clear();result.push(vertex);visualArray.pushItem(vertex);lineHighlighter.highlight(18);_context.next=27;return timer.wait(500);case 27:proceed=_context.sent;if(proceed){_context.next=30;break}return _context.abrupt("return");case 30:lineHighlighter.clear();if(_this.adjacencyList[vertex][0]){visualGraph.setPointerToVertex("adjacentVertex",_this.adjacencyList[vertex][0]);if(_this.adjacencyList[vertex][0]==="G"||_this.adjacencyList[vertex][0]===
"F"||_this.adjacencyList[vertex][0]==="E"||_this.adjacencyList[vertex][0]==="B")visualGraph.setPointerUp("adjacentVertex");else visualGraph.setPointerDown("adjacentVertex")}lineHighlighter.highlight(21);_context.next=35;return timer.wait(500);case 35:proceed=_context.sent;if(proceed){_context.next=38;break}return _context.abrupt("return");case 38:lineHighlighter.clear();firstIteration=true;_iterator=_createForOfIteratorHelper(_this.adjacencyList[vertex]);_context.prev=41;_iterator.s();case 43:if((_step=
_iterator.n()).done){_context.next=84;break}adjacentVertex=_step.value;if(!firstIteration){_context.next=49;break}firstIteration=false;_context.next=58;break;case 49:visualGraph.setPointerToVertex("adjacentVertex",adjacentVertex);if(adjacentVertex==="G"||adjacentVertex==="F"||adjacentVertex==="E"||adjacentVertex==="B")visualGraph.setPointerUp("adjacentVertex");else visualGraph.setPointerDown("adjacentVertex");lineHighlighter.highlight(21);_context.next=54;return timer.wait(500);case 54:proceed=_context.sent;
if(proceed){_context.next=57;break}return _context.abrupt("return");case 57:lineHighlighter.clear();case 58:lineHighlighter.highlight(23);_context.next=61;return timer.wait(500);case 61:proceed=_context.sent;if(proceed){_context.next=64;break}return _context.abrupt("return");case 64:lineHighlighter.clear();if(visited[adjacentVertex]){_context.next=79;break}_context.next=68;return df(adjacentVertex);case 68:visualGraph.setPointerToVertex("vertex",vertex);if(vertex==="G"||vertex==="F"||vertex==="E"||
vertex==="B")visualGraph.setPointerUp("vertex");else visualGraph.setPointerDown("vertex");visualGraph.setPointerToVertex("adjacentVertex",adjacentVertex);if(adjacentVertex==="G"||adjacentVertex==="F"||adjacentVertex==="E"||adjacentVertex==="B")visualGraph.setPointerUp("adjacentVertex");else visualGraph.setPointerDown("adjacentVertex");lineHighlighter.highlight(23);_context.next=75;return timer.wait(500);case 75:proceed=_context.sent;if(proceed){_context.next=78;break}return _context.abrupt("return");
case 78:lineHighlighter.clear();case 79:if(proceed){_context.next=81;break}return _context.abrupt("return");case 81:visualGraph.hidePointer("adjacentVertex");case 82:_context.next=43;break;case 84:_context.next=89;break;case 86:_context.prev=86;_context.t0=_context["catch"](41);_iterator.e(_context.t0);case 89:_context.prev=89;_iterator.f();return _context.finish(89);case 92:lineHighlighter.highlight(21);_context.next=95;return timer.wait(500);case 95:proceed=_context.sent;if(proceed){_context.next=
98;break}return _context.abrupt("return");case 98:lineHighlighter.clear();visualGraph.hidePointer("vertex");callStack.pop();case 101:case "end":return _context.stop()}},_callee,null,[[41,86,89,92]])}));return function df(_x7){return _ref2.apply(this,arguments)}}();lineHighlighter.highlight(27);_context2.next=30;return timer.wait(500);case 30:proceed=_context2.sent;if(proceed){_context2.next=33;break}return _context2.abrupt("return");case 33:lineHighlighter.clear();_context2.next=36;return df(startVertex);
case 36:if(proceed){_context2.next=38;break}return _context2.abrupt("return");case 38:lineHighlighter.highlight(27);_context2.next=41;return timer.wait(500);case 41:proceed=_context2.sent;if(proceed){_context2.next=44;break}return _context2.abrupt("return");case 44:lineHighlighter.clear();lineHighlighter.highlight(30);_context2.next=48;return timer.wait(500);case 48:proceed=_context2.sent;if(proceed){_context2.next=51;break}return _context2.abrupt("return");case 51:lineHighlighter.clear();visualGraph.hidePointer("startVertex");
callStack.pop();return _context2.abrupt("return",result);case 55:case "end":return _context2.stop()}},_callee2)}));return function(_x,_x2,_x3,_x4,_x5,_x6){return _ref.apply(this,arguments)}}();this.lineHighlighter.highlight(35);_context3.next=5;return this.timer.wait(500);case 5:proceed=_context3.sent;if(proceed){_context3.next=8;break}return _context3.abrupt("return");case 8:this.lineHighlighter.clear();graph.addVertex("A");graph.addVertex("B");graph.addVertex("C");graph.addVertex("D");graph.addVertex("E");
graph.addVertex("F");graph.addVertex("G");graph.addVertex("H");graph.addVertex("I");graph.addEdge("A","D");graph.addEdge("D","B");graph.addEdge("D","E");graph.addEdge("B","C");graph.addEdge("D","C");graph.addEdge("E","F");graph.addEdge("F","G");graph.addEdge("G","A");graph.addEdge("G","H");graph.addEdge("E","I");graph.addEdge("I","F");this.visualGraph.addVertex("A",215,0);this.visualGraph.addVertex("B",50,40);this.visualGraph.addVertex("C",50,110);this.visualGraph.addVertex("D",120,75);this.lineHighlighter.highlight(36);
_context3.next=36;return this.timer.wait(500);case 36:proceed=_context3.sent;if(proceed){_context3.next=39;break}return _context3.abrupt("return");case 39:this.lineHighlighter.clear();this.visualGraph.addVertex("E",215,150);this.visualGraph.addVertex("F",310,75);this.visualGraph.addVertex("G",380,40);this.visualGraph.addVertex("H",380,110);this.lineHighlighter.highlight(37);_context3.next=47;return this.timer.wait(500);case 47:proceed=_context3.sent;if(proceed){_context3.next=50;break}return _context3.abrupt("return");
case 50:this.lineHighlighter.clear();this.visualGraph.addVertex("I",330,115);this.lineHighlighter.highlight(38);_context3.next=55;return this.timer.wait(500);case 55:proceed=_context3.sent;if(proceed){_context3.next=58;break}return _context3.abrupt("return");case 58:this.lineHighlighter.clear();this.visualGraph.addEdge("A","D");this.visualGraph.addEdge("D","B");this.visualGraph.addEdge("D","E");this.visualGraph.addEdge("B","C");this.lineHighlighter.highlight(39);_context3.next=66;return this.timer.wait(500);
case 66:proceed=_context3.sent;if(proceed){_context3.next=69;break}return _context3.abrupt("return");case 69:this.lineHighlighter.clear();this.visualGraph.addEdge("D","C");this.visualGraph.addEdge("E","F");this.visualGraph.addEdge("F","G");this.visualGraph.addEdge("G","A");this.lineHighlighter.highlight(40);_context3.next=77;return this.timer.wait(500);case 77:proceed=_context3.sent;if(proceed){_context3.next=80;break}return _context3.abrupt("return");case 80:this.lineHighlighter.clear();this.visualGraph.addEdge("G",
"H");this.visualGraph.addEdge("E","I");this.visualGraph.addEdge("I","F");this.lineHighlighter.highlight(41);_context3.next=87;return this.timer.wait(500);case 87:proceed=_context3.sent;if(proceed){_context3.next=90;break}return _context3.abrupt("return");case 90:this.lineHighlighter.clear();this.lineHighlighter.highlight(44);_context3.next=94;return this.timer.wait(500);case 94:proceed=_context3.sent;if(proceed){_context3.next=97;break}return _context3.abrupt("return");case 97:this.lineHighlighter.clear();
_context3.next=100;return graph.exampleDFRecursive("D",this.lineHighlighter,this.timer,this.visualGraph,this.visualArray,this.callStack);case 100:vysledek=_context3.sent;if(proceed){_context3.next=103;break}return _context3.abrupt("return");case 103:this.lineHighlighter.highlight(44);_context3.next=106;return this.timer.wait(500);case 106:proceed=_context3.sent;if(proceed){_context3.next=109;break}return _context3.abrupt("return");case 109:this.lineHighlighter.clear();this.console.log("Graph se proch\u00e1zel v tomto po\u0159ad\u00ed:");
this.lineHighlighter.highlight(45);_context3.next=114;return this.timer.wait(500);case 114:proceed=_context3.sent;if(proceed){_context3.next=117;break}return _context3.abrupt("return");case 117:this.lineHighlighter.clear();this.console.log("["+vysledek+"]");this.lineHighlighter.highlight(46);_context3.next=122;return this.timer.wait(500);case 122:proceed=_context3.sent;if(proceed){_context3.next=125;break}return _context3.abrupt("return");case 125:this.lineHighlighter.clear();this.finish();case 127:case "end":return _context3.stop()}},
_callee3,this)}));function code(){return _code.apply(this,arguments)}return code}()},{exampleId:2,lineHighlighter:new LineHighlighter("code-2"),visualGraph:new VisualGraph("graph-2",["startVertex","currentVertex","neighbor"]),visualArray:new VisualArray("visual-array-2",9),visualLinkedList:new VisualLinkedList("stack-1"),timer:new Timer,console:new Console("console-2"),code:function(){var _code2=_asyncToGenerator(regeneratorRuntime.mark(function _callee5(){var proceed,graph,vysledek;return regeneratorRuntime.wrap(function _callee5$(_context5){while(1)switch(_context5.prev=
_context5.next){case 0:graph=new Graph;graph.exampleDFIterative=function(){var _ref3=_asyncToGenerator(regeneratorRuntime.mark(function _callee4(startVertex,lineHighlighter,timer,visualGraph,visualArray,visualLinkedList){var stack,result,visited,currentVertex,firstIteration,_iterator2,_step2,neighbor;return regeneratorRuntime.wrap(function _callee4$(_context4){while(1)switch(_context4.prev=_context4.next){case 0:visualGraph.setPointerToVertex("startVertex",startVertex);visualGraph.setPointerUp("startVertex");
stack=new Stack;lineHighlighter.highlight(6);_context4.next=6;return timer.wait(500);case 6:proceed=_context4.sent;if(proceed){_context4.next=9;break}return _context4.abrupt("return");case 9:lineHighlighter.clear();result=[];lineHighlighter.highlight(8);_context4.next=14;return timer.wait(500);case 14:proceed=_context4.sent;if(proceed){_context4.next=17;break}return _context4.abrupt("return");case 17:lineHighlighter.clear();visited={};lineHighlighter.highlight(10);_context4.next=22;return timer.wait(500);
case 22:proceed=_context4.sent;if(proceed){_context4.next=25;break}return _context4.abrupt("return");case 25:lineHighlighter.clear();lineHighlighter.highlight(12);_context4.next=29;return timer.wait(500);case 29:proceed=_context4.sent;if(proceed){_context4.next=32;break}return _context4.abrupt("return");case 32:lineHighlighter.clear();stack.push(startVertex);visualLinkedList.unshift(startVertex);visualLinkedList.get(0).setFirstStatus();lineHighlighter.highlight(15);_context4.next=39;return timer.wait(500);
case 39:proceed=_context4.sent;if(proceed){_context4.next=42;break}return _context4.abrupt("return");case 42:lineHighlighter.clear();visited[startVertex]=true;visualGraph.setVertexAsVisited(startVertex);lineHighlighter.highlight(16);_context4.next=48;return timer.wait(500);case 48:proceed=_context4.sent;if(proceed){_context4.next=51;break}return _context4.abrupt("return");case 51:lineHighlighter.clear();lineHighlighter.highlight(19);_context4.next=55;return timer.wait(500);case 55:proceed=_context4.sent;
if(proceed){_context4.next=58;break}return _context4.abrupt("return");case 58:lineHighlighter.clear();case 59:if(!(stack.size!==0)){_context4.next=164;break}currentVertex=stack.pop();visualLinkedList.shift();if(visualLinkedList.length!==0)visualLinkedList.get(0).setFirstStatus();visualGraph.setPointerToVertex("currentVertex",currentVertex);if(currentVertex==="G"||currentVertex==="F"||currentVertex==="E"||currentVertex==="B")visualGraph.setPointerUp("currentVertex");else visualGraph.setPointerDown("currentVertex");
lineHighlighter.highlight(21);_context4.next=68;return timer.wait(500);case 68:proceed=_context4.sent;if(proceed){_context4.next=71;break}return _context4.abrupt("return");case 71:lineHighlighter.clear();result.push(currentVertex);visualArray.pushItem(currentVertex);lineHighlighter.highlight(23);_context4.next=77;return timer.wait(500);case 77:proceed=_context4.sent;if(proceed){_context4.next=80;break}return _context4.abrupt("return");case 80:lineHighlighter.clear();firstIteration=true;if(this.adjacencyList[currentVertex][0]){visualGraph.setPointerToVertex("neighbor",
this.adjacencyList[currentVertex][0]);if(this.adjacencyList[currentVertex][0]==="G"||this.adjacencyList[currentVertex][0]==="F"||this.adjacencyList[currentVertex][0]==="E"||this.adjacencyList[currentVertex][0]==="B")visualGraph.setPointerUp("neighbor")}lineHighlighter.highlight(26);_context4.next=86;return timer.wait(500);case 86:proceed=_context4.sent;if(proceed){_context4.next=89;break}return _context4.abrupt("return");case 89:lineHighlighter.clear();_iterator2=_createForOfIteratorHelper(this.adjacencyList[currentVertex]);
_context4.prev=91;_iterator2.s();case 93:if((_step2=_iterator2.n()).done){_context4.next=140;break}neighbor=_step2.value;if(!firstIteration){_context4.next=99;break}firstIteration=false;_context4.next=108;break;case 99:visualGraph.setPointerToVertex("neighbor",neighbor);if(neighbor==="G"||neighbor==="F"||neighbor==="E"||neighbor==="B")visualGraph.setPointerUp("neighbor");lineHighlighter.highlight(26);_context4.next=104;return timer.wait(500);case 104:proceed=_context4.sent;if(proceed){_context4.next=
107;break}return _context4.abrupt("return");case 107:lineHighlighter.clear();case 108:lineHighlighter.highlight(28);_context4.next=111;return timer.wait(500);case 111:proceed=_context4.sent;if(proceed){_context4.next=114;break}return _context4.abrupt("return");case 114:lineHighlighter.clear();if(visited[neighbor]){_context4.next=136;break}stack.push(neighbor);visualLinkedList.unshift(neighbor);visualLinkedList.get(0).setFirstStatus();if(visualLinkedList.length>1){visualLinkedList.get(1).removeFirstStatus();
visualLinkedList.get(0).displayArrow()}lineHighlighter.highlight(29);_context4.next=123;return timer.wait(500);case 123:proceed=_context4.sent;if(proceed){_context4.next=126;break}return _context4.abrupt("return");case 126:lineHighlighter.clear();visited[neighbor]=true;visualGraph.setVertexAsVisited(neighbor);lineHighlighter.highlight(30);_context4.next=132;return timer.wait(500);case 132:proceed=_context4.sent;if(proceed){_context4.next=135;break}return _context4.abrupt("return");case 135:lineHighlighter.clear();
case 136:visualGraph.hidePointer("neighbor");visualGraph.setPointerDown("neighbor");case 138:_context4.next=93;break;case 140:_context4.next=145;break;case 142:_context4.prev=142;_context4.t0=_context4["catch"](91);_iterator2.e(_context4.t0);case 145:_context4.prev=145;_iterator2.f();return _context4.finish(145);case 148:lineHighlighter.highlight(26);_context4.next=151;return timer.wait(500);case 151:proceed=_context4.sent;if(proceed){_context4.next=154;break}return _context4.abrupt("return");case 154:lineHighlighter.clear();
lineHighlighter.highlight(19);_context4.next=158;return timer.wait(500);case 158:proceed=_context4.sent;if(proceed){_context4.next=161;break}return _context4.abrupt("return");case 161:lineHighlighter.clear();_context4.next=59;break;case 164:lineHighlighter.highlight(36);_context4.next=167;return timer.wait(500);case 167:proceed=_context4.sent;if(proceed){_context4.next=170;break}return _context4.abrupt("return");case 170:lineHighlighter.clear();visualGraph.hidePointer("startVertex");visualGraph.hidePointer("currentVertex");
return _context4.abrupt("return",result);case 174:case "end":return _context4.stop()}},_callee4,this,[[91,142,145,148]])}));return function(_x8,_x9,_x10,_x11,_x12,_x13){return _ref3.apply(this,arguments)}}();this.lineHighlighter.highlight(41);_context5.next=5;return this.timer.wait(500);case 5:proceed=_context5.sent;if(proceed){_context5.next=8;break}return _context5.abrupt("return");case 8:this.lineHighlighter.clear();graph.addVertex("A");graph.addVertex("B");graph.addVertex("C");graph.addVertex("D");
graph.addVertex("E");graph.addVertex("F");graph.addVertex("G");graph.addVertex("H");graph.addVertex("I");graph.addEdge("A","D");graph.addEdge("D","B");graph.addEdge("D","E");graph.addEdge("B","C");graph.addEdge("D","C");graph.addEdge("E","F");graph.addEdge("F","G");graph.addEdge("G","A");graph.addEdge("G","H");graph.addEdge("E","I");graph.addEdge("I","F");this.visualGraph.addVertex("A",215,0);this.visualGraph.addVertex("B",50,40);this.visualGraph.addVertex("C",50,110);this.visualGraph.addVertex("D",
120,75);this.lineHighlighter.highlight(42);_context5.next=36;return this.timer.wait(500);case 36:proceed=_context5.sent;if(proceed){_context5.next=39;break}return _context5.abrupt("return");case 39:this.lineHighlighter.clear();this.visualGraph.addVertex("E",215,150);this.visualGraph.addVertex("F",310,75);this.visualGraph.addVertex("G",380,40);this.visualGraph.addVertex("H",380,110);this.lineHighlighter.highlight(43);_context5.next=47;return this.timer.wait(500);case 47:proceed=_context5.sent;if(proceed){_context5.next=
50;break}return _context5.abrupt("return");case 50:this.lineHighlighter.clear();this.visualGraph.addVertex("I",330,115);this.lineHighlighter.highlight(44);_context5.next=55;return this.timer.wait(500);case 55:proceed=_context5.sent;if(proceed){_context5.next=58;break}return _context5.abrupt("return");case 58:this.lineHighlighter.clear();this.visualGraph.addEdge("A","D");this.visualGraph.addEdge("D","B");this.visualGraph.addEdge("D","E");this.visualGraph.addEdge("B","C");this.lineHighlighter.highlight(45);
_context5.next=66;return this.timer.wait(500);case 66:proceed=_context5.sent;if(proceed){_context5.next=69;break}return _context5.abrupt("return");case 69:this.lineHighlighter.clear();this.visualGraph.addEdge("D","C");this.visualGraph.addEdge("E","F");this.visualGraph.addEdge("F","G");this.visualGraph.addEdge("G","A");this.lineHighlighter.highlight(46);_context5.next=77;return this.timer.wait(500);case 77:proceed=_context5.sent;if(proceed){_context5.next=80;break}return _context5.abrupt("return");
case 80:this.lineHighlighter.clear();this.visualGraph.addEdge("G","H");this.visualGraph.addEdge("E","I");this.visualGraph.addEdge("I","F");this.lineHighlighter.highlight(47);_context5.next=87;return this.timer.wait(500);case 87:proceed=_context5.sent;if(proceed){_context5.next=90;break}return _context5.abrupt("return");case 90:this.lineHighlighter.clear();this.lineHighlighter.highlight(50);_context5.next=94;return this.timer.wait(500);case 94:proceed=_context5.sent;if(proceed){_context5.next=97;break}return _context5.abrupt("return");
case 97:this.lineHighlighter.clear();_context5.next=100;return graph.exampleDFIterative("D",this.lineHighlighter,this.timer,this.visualGraph,this.visualArray,this.visualLinkedList);case 100:vysledek=_context5.sent;if(proceed){_context5.next=103;break}return _context5.abrupt("return");case 103:this.lineHighlighter.highlight(50);_context5.next=106;return this.timer.wait(500);case 106:proceed=_context5.sent;if(proceed){_context5.next=109;break}return _context5.abrupt("return");case 109:this.lineHighlighter.clear();
this.console.log("Graph se proch\u00e1zel v tomto po\u0159ad\u00ed:");this.lineHighlighter.highlight(51);_context5.next=114;return this.timer.wait(500);case 114:proceed=_context5.sent;if(proceed){_context5.next=117;break}return _context5.abrupt("return");case 117:this.lineHighlighter.clear();this.console.log("["+vysledek+"]");this.lineHighlighter.highlight(52);_context5.next=122;return this.timer.wait(500);case 122:proceed=_context5.sent;if(proceed){_context5.next=125;break}return _context5.abrupt("return");
case 125:this.lineHighlighter.clear();this.finish();case 127:case "end":return _context5.stop()}},_callee5,this)}));function code(){return _code2.apply(this,arguments)}return code}()},{exampleId:3,lineHighlighter:new LineHighlighter("code-3"),visualGraph:new VisualGraph("graph-3",["startVertex","currentVertex","neighbor"]),visualArray:new VisualArray("visual-array-3",9),visualLinkedList:new VisualLinkedList("queue-1"),timer:new Timer,console:new Console("console-3"),code:function(){var _code3=_asyncToGenerator(regeneratorRuntime.mark(function _callee7(){var proceed,
graph,vysledek;return regeneratorRuntime.wrap(function _callee7$(_context7){while(1)switch(_context7.prev=_context7.next){case 0:graph=new Graph;graph.exampleBF=function(){var _ref4=_asyncToGenerator(regeneratorRuntime.mark(function _callee6(startVertex,lineHighlighter,timer,visualGraph,visualArray,visualLinkedList){var queue,result,visited,currentVertex,firstIteration,_iterator3,_step3,neighbor;return regeneratorRuntime.wrap(function _callee6$(_context6){while(1)switch(_context6.prev=_context6.next){case 0:visualGraph.setPointerToVertex("startVertex",
startVertex);visualGraph.setPointerUp("startVertex");queue=new Queue;lineHighlighter.highlight(6);_context6.next=6;return timer.wait(500);case 6:proceed=_context6.sent;if(proceed){_context6.next=9;break}return _context6.abrupt("return");case 9:lineHighlighter.clear();result=[];lineHighlighter.highlight(8);_context6.next=14;return timer.wait(500);case 14:proceed=_context6.sent;if(proceed){_context6.next=17;break}return _context6.abrupt("return");case 17:lineHighlighter.clear();visited={};lineHighlighter.highlight(10);
_context6.next=22;return timer.wait(500);case 22:proceed=_context6.sent;if(proceed){_context6.next=25;break}return _context6.abrupt("return");case 25:lineHighlighter.clear();lineHighlighter.highlight(12);_context6.next=29;return timer.wait(500);case 29:proceed=_context6.sent;if(proceed){_context6.next=32;break}return _context6.abrupt("return");case 32:lineHighlighter.clear();queue.enqueue(startVertex);visualLinkedList.push(startVertex);visualLinkedList.get(0).setFirstStatus();visualLinkedList.get(0).setLastStatus();
lineHighlighter.highlight(15);_context6.next=40;return timer.wait(500);case 40:proceed=_context6.sent;if(proceed){_context6.next=43;break}return _context6.abrupt("return");case 43:lineHighlighter.clear();visited[startVertex]=true;visualGraph.setVertexAsVisited(startVertex);lineHighlighter.highlight(16);_context6.next=49;return timer.wait(500);case 49:proceed=_context6.sent;if(proceed){_context6.next=52;break}return _context6.abrupt("return");case 52:lineHighlighter.clear();lineHighlighter.highlight(19);
_context6.next=56;return timer.wait(500);case 56:proceed=_context6.sent;if(proceed){_context6.next=59;break}return _context6.abrupt("return");case 59:lineHighlighter.clear();case 60:if(!(queue.size!==0)){_context6.next=165;break}currentVertex=queue.dequeue();visualLinkedList.shift();if(visualLinkedList.length!==0)visualLinkedList.get(0).setFirstStatus();visualGraph.setPointerToVertex("currentVertex",currentVertex);if(currentVertex==="G"||currentVertex==="F"||currentVertex==="E"||currentVertex==="B")visualGraph.setPointerUp("currentVertex");
else visualGraph.setPointerDown("currentVertex");lineHighlighter.highlight(21);_context6.next=69;return timer.wait(500);case 69:proceed=_context6.sent;if(proceed){_context6.next=72;break}return _context6.abrupt("return");case 72:lineHighlighter.clear();result.push(currentVertex);visualArray.pushItem(currentVertex);lineHighlighter.highlight(23);_context6.next=78;return timer.wait(500);case 78:proceed=_context6.sent;if(proceed){_context6.next=81;break}return _context6.abrupt("return");case 81:lineHighlighter.clear();
firstIteration=true;if(this.adjacencyList[currentVertex][0]){visualGraph.setPointerToVertex("neighbor",this.adjacencyList[currentVertex][0]);if(this.adjacencyList[currentVertex][0]==="G"||this.adjacencyList[currentVertex][0]==="F"||this.adjacencyList[currentVertex][0]==="E"||this.adjacencyList[currentVertex][0]==="B")visualGraph.setPointerUp("neighbor")}lineHighlighter.highlight(26);_context6.next=87;return timer.wait(500);case 87:proceed=_context6.sent;if(proceed){_context6.next=90;break}return _context6.abrupt("return");
case 90:lineHighlighter.clear();_iterator3=_createForOfIteratorHelper(this.adjacencyList[currentVertex]);_context6.prev=92;_iterator3.s();case 94:if((_step3=_iterator3.n()).done){_context6.next=141;break}neighbor=_step3.value;if(!firstIteration){_context6.next=100;break}firstIteration=false;_context6.next=109;break;case 100:visualGraph.setPointerToVertex("neighbor",neighbor);if(neighbor==="G"||neighbor==="F"||neighbor==="E"||neighbor==="B")visualGraph.setPointerUp("neighbor");lineHighlighter.highlight(26);
_context6.next=105;return timer.wait(500);case 105:proceed=_context6.sent;if(proceed){_context6.next=108;break}return _context6.abrupt("return");case 108:lineHighlighter.clear();case 109:lineHighlighter.highlight(28);_context6.next=112;return timer.wait(500);case 112:proceed=_context6.sent;if(proceed){_context6.next=115;break}return _context6.abrupt("return");case 115:lineHighlighter.clear();if(visited[neighbor]){_context6.next=137;break}queue.enqueue(neighbor);visualLinkedList.push(neighbor);visualLinkedList.get(visualLinkedList.length-
1).setLastStatus();if(visualLinkedList.length>1){visualLinkedList.get(visualLinkedList.length-2).removeLastStatus();visualLinkedList.get(visualLinkedList.length-2).displayArrow()}else visualLinkedList.get(0).setFirstStatus();lineHighlighter.highlight(29);_context6.next=124;return timer.wait(500);case 124:proceed=_context6.sent;if(proceed){_context6.next=127;break}return _context6.abrupt("return");case 127:lineHighlighter.clear();visited[neighbor]=true;visualGraph.setVertexAsVisited(neighbor);lineHighlighter.highlight(30);
_context6.next=133;return timer.wait(500);case 133:proceed=_context6.sent;if(proceed){_context6.next=136;break}return _context6.abrupt("return");case 136:lineHighlighter.clear();case 137:visualGraph.hidePointer("neighbor");visualGraph.setPointerDown("neighbor");case 139:_context6.next=94;break;case 141:_context6.next=146;break;case 143:_context6.prev=143;_context6.t0=_context6["catch"](92);_iterator3.e(_context6.t0);case 146:_context6.prev=146;_iterator3.f();return _context6.finish(146);case 149:lineHighlighter.highlight(26);
_context6.next=152;return timer.wait(500);case 152:proceed=_context6.sent;if(proceed){_context6.next=155;break}return _context6.abrupt("return");case 155:lineHighlighter.clear();lineHighlighter.highlight(19);_context6.next=159;return timer.wait(500);case 159:proceed=_context6.sent;if(proceed){_context6.next=162;break}return _context6.abrupt("return");case 162:lineHighlighter.clear();_context6.next=60;break;case 165:lineHighlighter.highlight(36);_context6.next=168;return timer.wait(500);case 168:proceed=
_context6.sent;if(proceed){_context6.next=171;break}return _context6.abrupt("return");case 171:lineHighlighter.clear();visualGraph.hidePointer("startVertex");visualGraph.hidePointer("currentVertex");return _context6.abrupt("return",result);case 175:case "end":return _context6.stop()}},_callee6,this,[[92,143,146,149]])}));return function(_x14,_x15,_x16,_x17,_x18,_x19){return _ref4.apply(this,arguments)}}();this.lineHighlighter.highlight(41);_context7.next=5;return this.timer.wait(500);case 5:proceed=
_context7.sent;if(proceed){_context7.next=8;break}return _context7.abrupt("return");case 8:this.lineHighlighter.clear();graph.addVertex("A");graph.addVertex("B");graph.addVertex("C");graph.addVertex("D");graph.addVertex("E");graph.addVertex("F");graph.addVertex("G");graph.addVertex("H");graph.addVertex("I");graph.addEdge("A","D");graph.addEdge("D","B");graph.addEdge("D","E");graph.addEdge("B","C");graph.addEdge("D","C");graph.addEdge("E","F");graph.addEdge("F","G");graph.addEdge("G","A");graph.addEdge("G",
"H");graph.addEdge("E","I");graph.addEdge("I","F");this.visualGraph.addVertex("A",215,0);this.visualGraph.addVertex("B",50,40);this.visualGraph.addVertex("C",50,110);this.visualGraph.addVertex("D",120,75);this.lineHighlighter.highlight(42);_context7.next=36;return this.timer.wait(500);case 36:proceed=_context7.sent;if(proceed){_context7.next=39;break}return _context7.abrupt("return");case 39:this.lineHighlighter.clear();this.visualGraph.addVertex("E",215,150);this.visualGraph.addVertex("F",310,75);
this.visualGraph.addVertex("G",380,40);this.visualGraph.addVertex("H",380,110);this.lineHighlighter.highlight(43);_context7.next=47;return this.timer.wait(500);case 47:proceed=_context7.sent;if(proceed){_context7.next=50;break}return _context7.abrupt("return");case 50:this.lineHighlighter.clear();this.visualGraph.addVertex("I",330,115);this.lineHighlighter.highlight(44);_context7.next=55;return this.timer.wait(500);case 55:proceed=_context7.sent;if(proceed){_context7.next=58;break}return _context7.abrupt("return");
case 58:this.lineHighlighter.clear();this.visualGraph.addEdge("A","D");this.visualGraph.addEdge("D","B");this.visualGraph.addEdge("D","E");this.visualGraph.addEdge("B","C");this.lineHighlighter.highlight(45);_context7.next=66;return this.timer.wait(500);case 66:proceed=_context7.sent;if(proceed){_context7.next=69;break}return _context7.abrupt("return");case 69:this.lineHighlighter.clear();this.visualGraph.addEdge("D","C");this.visualGraph.addEdge("E","F");this.visualGraph.addEdge("F","G");this.visualGraph.addEdge("G",
"A");this.lineHighlighter.highlight(46);_context7.next=77;return this.timer.wait(500);case 77:proceed=_context7.sent;if(proceed){_context7.next=80;break}return _context7.abrupt("return");case 80:this.lineHighlighter.clear();this.visualGraph.addEdge("G","H");this.visualGraph.addEdge("E","I");this.visualGraph.addEdge("I","F");this.lineHighlighter.highlight(47);_context7.next=87;return this.timer.wait(500);case 87:proceed=_context7.sent;if(proceed){_context7.next=90;break}return _context7.abrupt("return");
case 90:this.lineHighlighter.clear();this.lineHighlighter.highlight(50);_context7.next=94;return this.timer.wait(500);case 94:proceed=_context7.sent;if(proceed){_context7.next=97;break}return _context7.abrupt("return");case 97:this.lineHighlighter.clear();_context7.next=100;return graph.exampleBF("D",this.lineHighlighter,this.timer,this.visualGraph,this.visualArray,this.visualLinkedList);case 100:vysledek=_context7.sent;if(proceed){_context7.next=103;break}return _context7.abrupt("return");case 103:this.lineHighlighter.highlight(50);
_context7.next=106;return this.timer.wait(500);case 106:proceed=_context7.sent;if(proceed){_context7.next=109;break}return _context7.abrupt("return");case 109:this.lineHighlighter.clear();this.console.log("Graph se proch\u00e1zel v tomto po\u0159ad\u00ed:");this.lineHighlighter.highlight(51);_context7.next=114;return this.timer.wait(500);case 114:proceed=_context7.sent;if(proceed){_context7.next=117;break}return _context7.abrupt("return");case 117:this.lineHighlighter.clear();this.console.log("["+
vysledek+"]");this.lineHighlighter.highlight(52);_context7.next=122;return this.timer.wait(500);case 122:proceed=_context7.sent;if(proceed){_context7.next=125;break}return _context7.abrupt("return");case 125:this.lineHighlighter.clear();this.finish();case 127:case "end":return _context7.stop()}},_callee7,this)}));function code(){return _code3.apply(this,arguments)}return code}()}];initExamples(config);