function asyncGeneratorStep(gen,resolve,reject,_next,_throw,key,arg){try{var info=gen[key](arg);var value=info.value}catch(error){reject(error);return}if(info.done)resolve(value);else Promise.resolve(value).then(_next,_throw)}
function _asyncToGenerator(fn){return function(){var self=this,args=arguments;return new Promise(function(resolve,reject){var gen=fn.apply(self,args);function _next(value){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"next",value)}function _throw(err){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"throw",err)}_next(undefined)})}}
function _defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor)}}
function _createClass(Constructor,protoProps,staticProps){if(protoProps)_defineProperties(Constructor.prototype,protoProps);if(staticProps)_defineProperties(Constructor,staticProps);Object.defineProperty(Constructor,"prototype",{writable:false});return Constructor}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor))throw new TypeError("Cannot call a class as a function");}var LineHighlighter=InteractiveExample.LineHighlighter;var Timer=InteractiveExample.Timer;
var initExamples=InteractiveExample.initExamples;var VisualLinkedList=InteractiveExample.VisualLinkedList;var Node=_createClass(function Node(value){_classCallCheck(this,Node);this.value=value;this.next=null});
var Stack=function(){function Stack(){_classCallCheck(this,Stack);this.first=null;this.size=0}_createClass(Stack,[{key:"push",value:function push(value){var newNode=new Node(value);if(!this.first)this.first=newNode;else{newNode.next=this.first;this.first=newNode}return++this.size}},{key:"pop",value:function pop(){if(!this.first)return null;var value=this.first.value;this.first=this.first.next;this.size--;return value}}]);return Stack}();
var Queue=function(){function Queue(){_classCallCheck(this,Queue);this.first=null;this.last=null;this.size=0}_createClass(Queue,[{key:"enqueue",value:function enqueue(value){var newNode=new Node(value);if(!this.first){this.first=newNode;this.last=newNode}else{this.last.next=newNode;this.last=newNode}return++this.size}},{key:"dequeue",value:function dequeue(){if(!this.first)return null;var value=this.first.value;if(this.first===this.last)this.last=null;this.first=this.first.next;this.size--;return value}}]);
return Queue}();
var config=[{exampleId:1,visualLinkedList:new VisualLinkedList("linked-list-1",["newNode"]),lineHighlighter:new LineHighlighter("code-1"),timer:new Timer,code:function(){var _code=_asyncToGenerator(regeneratorRuntime.mark(function _callee2(){var proceed,stack;return regeneratorRuntime.wrap(function _callee2$(_context2){while(1)switch(_context2.prev=_context2.next){case 0:stack=new Stack;stack.examplePush=function(){var _ref=_asyncToGenerator(regeneratorRuntime.mark(function _callee(value,lineHighlighter,
timer,visualLinkedList){var newNode;return regeneratorRuntime.wrap(function _callee$(_context){while(1)switch(_context.prev=_context.next){case 0:newNode=new Node(value);visualLinkedList.unshift(value);visualLinkedList.showPointer("newNode");visualLinkedList.movePointerToNode("newNode",0);lineHighlighter.highlight(6);_context.next=7;return timer.wait(500);case 7:proceed=_context.sent;if(proceed){_context.next=10;break}return _context.abrupt("return");case 10:lineHighlighter.clear();lineHighlighter.highlight(8);
_context.next=14;return timer.wait(500);case 14:proceed=_context.sent;if(proceed){_context.next=17;break}return _context.abrupt("return");case 17:lineHighlighter.clear();if(this.first){_context.next=30;break}this.first=newNode;visualLinkedList.get(0).setFirstStatus();lineHighlighter.highlight(10);_context.next=24;return timer.wait(500);case 24:proceed=_context.sent;if(proceed){_context.next=27;break}return _context.abrupt("return");case 27:lineHighlighter.clear();_context.next=49;break;case 30:newNode.next=
this.first;visualLinkedList.get(0).displayArrow();lineHighlighter.highlight(13);_context.next=35;return timer.wait(500);case 35:proceed=_context.sent;if(proceed){_context.next=38;break}return _context.abrupt("return");case 38:lineHighlighter.clear();this.first=newNode;visualLinkedList.get(1).removeFirstStatus();visualLinkedList.get(0).setFirstStatus();lineHighlighter.highlight(15);_context.next=45;return timer.wait(500);case 45:proceed=_context.sent;if(proceed){_context.next=48;break}return _context.abrupt("return");
case 48:lineHighlighter.clear();case 49:lineHighlighter.highlight(19);_context.next=52;return timer.wait(500);case 52:proceed=_context.sent;if(proceed){_context.next=55;break}return _context.abrupt("return");case 55:lineHighlighter.clear();visualLinkedList.hidePointer("newNode");return _context.abrupt("return",++this.size);case 58:case "end":return _context.stop()}},_callee,this)}));return function(_x,_x2,_x3,_x4){return _ref.apply(this,arguments)}}();this.lineHighlighter.highlight(24);_context2.next=
5;return this.timer.wait(500);case 5:proceed=_context2.sent;if(proceed){_context2.next=8;break}return _context2.abrupt("return");case 8:this.lineHighlighter.clear();this.lineHighlighter.highlight(27);_context2.next=12;return this.timer.wait(500);case 12:proceed=_context2.sent;if(proceed){_context2.next=15;break}return _context2.abrupt("return");case 15:this.lineHighlighter.clear();_context2.next=18;return stack.examplePush(25,this.lineHighlighter,this.timer,this.visualLinkedList);case 18:if(proceed){_context2.next=
20;break}return _context2.abrupt("return");case 20:this.lineHighlighter.highlight(27);_context2.next=23;return this.timer.wait(500);case 23:proceed=_context2.sent;if(proceed){_context2.next=26;break}return _context2.abrupt("return");case 26:this.lineHighlighter.clear();this.lineHighlighter.highlight(29);_context2.next=30;return this.timer.wait(500);case 30:proceed=_context2.sent;if(proceed){_context2.next=33;break}return _context2.abrupt("return");case 33:this.lineHighlighter.clear();_context2.next=
36;return stack.examplePush(5,this.lineHighlighter,this.timer,this.visualLinkedList);case 36:if(proceed){_context2.next=38;break}return _context2.abrupt("return");case 38:this.lineHighlighter.highlight(29);_context2.next=41;return this.timer.wait(500);case 41:proceed=_context2.sent;if(proceed){_context2.next=44;break}return _context2.abrupt("return");case 44:this.lineHighlighter.clear();this.lineHighlighter.highlight(30);_context2.next=48;return this.timer.wait(500);case 48:proceed=_context2.sent;
if(proceed){_context2.next=51;break}return _context2.abrupt("return");case 51:this.lineHighlighter.clear();_context2.next=54;return stack.examplePush(true,this.lineHighlighter,this.timer,this.visualLinkedList);case 54:if(proceed){_context2.next=56;break}return _context2.abrupt("return");case 56:this.lineHighlighter.highlight(30);_context2.next=59;return this.timer.wait(500);case 59:proceed=_context2.sent;if(proceed){_context2.next=62;break}return _context2.abrupt("return");case 62:this.lineHighlighter.clear();
this.finish();case 64:case "end":return _context2.stop()}},_callee2,this)}));function code(){return _code.apply(this,arguments)}return code}()},{exampleId:2,visualLinkedList:new VisualLinkedList("linked-list-2"),lineHighlighter:new LineHighlighter("code-2"),timer:new Timer,code:function(){var _code2=_asyncToGenerator(regeneratorRuntime.mark(function _callee4(){var proceed,stack;return regeneratorRuntime.wrap(function _callee4$(_context4){while(1)switch(_context4.prev=_context4.next){case 0:stack=
new Stack;stack.examplePop=function(){var _ref2=_asyncToGenerator(regeneratorRuntime.mark(function _callee3(lineHighlighter,timer,visualLinkedList){var value;return regeneratorRuntime.wrap(function _callee3$(_context3){while(1)switch(_context3.prev=_context3.next){case 0:lineHighlighter.highlight(6);_context3.next=3;return timer.wait(500);case 3:proceed=_context3.sent;if(proceed){_context3.next=6;break}return _context3.abrupt("return");case 6:lineHighlighter.clear();if(this.first){_context3.next=
9;break}return _context3.abrupt("return",null);case 9:value=this.first.value;lineHighlighter.highlight(9);_context3.next=13;return timer.wait(500);case 13:proceed=_context3.sent;if(proceed){_context3.next=16;break}return _context3.abrupt("return");case 16:lineHighlighter.clear();this.first=this.first.next;if(this.size!==1){visualLinkedList.get(0).removeFirstStatus();visualLinkedList.get(1).setFirstStatus()}lineHighlighter.highlight(12);_context3.next=22;return timer.wait(500);case 22:proceed=_context3.sent;
if(proceed){_context3.next=25;break}return _context3.abrupt("return");case 25:lineHighlighter.clear();this.size--;lineHighlighter.highlight(14);_context3.next=30;return timer.wait(500);case 30:proceed=_context3.sent;if(proceed){_context3.next=33;break}return _context3.abrupt("return");case 33:lineHighlighter.clear();lineHighlighter.highlight(17);_context3.next=37;return timer.wait(500);case 37:proceed=_context3.sent;if(proceed){_context3.next=40;break}return _context3.abrupt("return");case 40:lineHighlighter.clear();
visualLinkedList.shift();return _context3.abrupt("return",value);case 43:case "end":return _context3.stop()}},_callee3,this)}));return function(_x5,_x6,_x7){return _ref2.apply(this,arguments)}}();this.lineHighlighter.highlight(21);_context4.next=5;return this.timer.wait(500);case 5:proceed=_context4.sent;if(proceed){_context4.next=8;break}return _context4.abrupt("return");case 8:this.lineHighlighter.clear();stack.push(25);this.visualLinkedList.unshift(25);this.visualLinkedList.get(0).setFirstStatus();
this.lineHighlighter.highlight(24);_context4.next=15;return this.timer.wait(500);case 15:proceed=_context4.sent;if(proceed){_context4.next=18;break}return _context4.abrupt("return");case 18:this.lineHighlighter.clear();stack.push(5);this.visualLinkedList.unshift(5);this.visualLinkedList.get(1).removeFirstStatus();this.visualLinkedList.get(0).displayArrow();this.visualLinkedList.get(0).setFirstStatus();this.lineHighlighter.highlight(25);_context4.next=27;return this.timer.wait(500);case 27:proceed=
_context4.sent;if(proceed){_context4.next=30;break}return _context4.abrupt("return");case 30:this.lineHighlighter.clear();stack.push(true);this.visualLinkedList.unshift(true);this.visualLinkedList.get(1).removeFirstStatus();this.visualLinkedList.get(0).displayArrow();this.visualLinkedList.get(0).setFirstStatus();this.lineHighlighter.highlight(26);_context4.next=39;return this.timer.wait(500);case 39:proceed=_context4.sent;if(proceed){_context4.next=42;break}return _context4.abrupt("return");case 42:this.lineHighlighter.clear();
this.lineHighlighter.highlight(29);_context4.next=46;return this.timer.wait(500);case 46:proceed=_context4.sent;if(proceed){_context4.next=49;break}return _context4.abrupt("return");case 49:this.lineHighlighter.clear();_context4.next=52;return stack.examplePop(this.lineHighlighter,this.timer,this.visualLinkedList);case 52:if(proceed){_context4.next=54;break}return _context4.abrupt("return");case 54:this.lineHighlighter.highlight(29);_context4.next=57;return this.timer.wait(500);case 57:proceed=_context4.sent;
if(proceed){_context4.next=60;break}return _context4.abrupt("return");case 60:this.lineHighlighter.clear();stack.push(23);this.visualLinkedList.unshift(23);this.visualLinkedList.get(1).removeFirstStatus();this.visualLinkedList.get(0).displayArrow();this.visualLinkedList.get(0).setFirstStatus();this.lineHighlighter.highlight(32);_context4.next=69;return this.timer.wait(500);case 69:proceed=_context4.sent;if(proceed){_context4.next=72;break}return _context4.abrupt("return");case 72:this.lineHighlighter.clear();
this.lineHighlighter.highlight(35);_context4.next=76;return this.timer.wait(500);case 76:proceed=_context4.sent;if(proceed){_context4.next=79;break}return _context4.abrupt("return");case 79:this.lineHighlighter.clear();_context4.next=82;return stack.examplePop(this.lineHighlighter,this.timer,this.visualLinkedList);case 82:if(proceed){_context4.next=84;break}return _context4.abrupt("return");case 84:this.lineHighlighter.highlight(35);_context4.next=87;return this.timer.wait(500);case 87:proceed=_context4.sent;
if(proceed){_context4.next=90;break}return _context4.abrupt("return");case 90:this.lineHighlighter.clear();this.lineHighlighter.highlight(36);_context4.next=94;return this.timer.wait(500);case 94:proceed=_context4.sent;if(proceed){_context4.next=97;break}return _context4.abrupt("return");case 97:this.lineHighlighter.clear();_context4.next=100;return stack.examplePop(this.lineHighlighter,this.timer,this.visualLinkedList);case 100:if(proceed){_context4.next=102;break}return _context4.abrupt("return");
case 102:this.lineHighlighter.highlight(36);_context4.next=105;return this.timer.wait(500);case 105:proceed=_context4.sent;if(proceed){_context4.next=108;break}return _context4.abrupt("return");case 108:this.lineHighlighter.clear();this.finish();case 110:case "end":return _context4.stop()}},_callee4,this)}));function code(){return _code2.apply(this,arguments)}return code}()},{exampleId:3,visualLinkedList:new VisualLinkedList("linked-list-3",["newNode"]),lineHighlighter:new LineHighlighter("code-3"),
timer:new Timer,code:function(){var _code3=_asyncToGenerator(regeneratorRuntime.mark(function _callee6(){var proceed,queue;return regeneratorRuntime.wrap(function _callee6$(_context6){while(1)switch(_context6.prev=_context6.next){case 0:queue=new Queue;queue.exampleEnqueue=function(){var _ref3=_asyncToGenerator(regeneratorRuntime.mark(function _callee5(value,lineHighlighter,timer,visualLinkedList){var newNode;return regeneratorRuntime.wrap(function _callee5$(_context5){while(1)switch(_context5.prev=
_context5.next){case 0:newNode=new Node(value);visualLinkedList.push(value);visualLinkedList.showPointer("newNode");visualLinkedList.movePointerToNode("newNode",this.size);lineHighlighter.highlight(6);_context5.next=7;return timer.wait(500);case 7:proceed=_context5.sent;if(proceed){_context5.next=10;break}return _context5.abrupt("return");case 10:lineHighlighter.clear();lineHighlighter.highlight(8);_context5.next=14;return timer.wait(500);case 14:proceed=_context5.sent;if(proceed){_context5.next=
17;break}return _context5.abrupt("return");case 17:lineHighlighter.clear();if(this.first){_context5.next=39;break}this.first=newNode;visualLinkedList.get(0).setFirstStatus();lineHighlighter.highlight(10);_context5.next=24;return timer.wait(500);case 24:proceed=_context5.sent;if(proceed){_context5.next=27;break}return _context5.abrupt("return");case 27:lineHighlighter.clear();this.last=newNode;visualLinkedList.get(0).setLastStatus();lineHighlighter.highlight(11);_context5.next=33;return timer.wait(500);
case 33:proceed=_context5.sent;if(proceed){_context5.next=36;break}return _context5.abrupt("return");case 36:lineHighlighter.clear();_context5.next=58;break;case 39:this.last.next=newNode;visualLinkedList.get(this.size-1).displayArrow();lineHighlighter.highlight(14);_context5.next=44;return timer.wait(500);case 44:proceed=_context5.sent;if(proceed){_context5.next=47;break}return _context5.abrupt("return");case 47:lineHighlighter.clear();this.last=newNode;visualLinkedList.get(this.size-1).removeLastStatus();
visualLinkedList.get(this.size).setLastStatus();lineHighlighter.highlight(16);_context5.next=54;return timer.wait(500);case 54:proceed=_context5.sent;if(proceed){_context5.next=57;break}return _context5.abrupt("return");case 57:lineHighlighter.clear();case 58:lineHighlighter.highlight(19);_context5.next=61;return timer.wait(500);case 61:proceed=_context5.sent;if(proceed){_context5.next=64;break}return _context5.abrupt("return");case 64:lineHighlighter.clear();visualLinkedList.hidePointer("newNode");
return _context5.abrupt("return",++this.size);case 67:case "end":return _context5.stop()}},_callee5,this)}));return function(_x8,_x9,_x10,_x11){return _ref3.apply(this,arguments)}}();this.lineHighlighter.highlight(24);_context6.next=5;return this.timer.wait(500);case 5:proceed=_context6.sent;if(proceed){_context6.next=8;break}return _context6.abrupt("return");case 8:this.lineHighlighter.clear();this.lineHighlighter.highlight(27);_context6.next=12;return this.timer.wait(500);case 12:proceed=_context6.sent;
if(proceed){_context6.next=15;break}return _context6.abrupt("return");case 15:this.lineHighlighter.clear();_context6.next=18;return queue.exampleEnqueue(25,this.lineHighlighter,this.timer,this.visualLinkedList);case 18:if(proceed){_context6.next=20;break}return _context6.abrupt("return");case 20:this.lineHighlighter.highlight(27);_context6.next=23;return this.timer.wait(500);case 23:proceed=_context6.sent;if(proceed){_context6.next=26;break}return _context6.abrupt("return");case 26:this.lineHighlighter.clear();
this.lineHighlighter.highlight(29);_context6.next=30;return this.timer.wait(500);case 30:proceed=_context6.sent;if(proceed){_context6.next=33;break}return _context6.abrupt("return");case 33:this.lineHighlighter.clear();_context6.next=36;return queue.exampleEnqueue(5,this.lineHighlighter,this.timer,this.visualLinkedList);case 36:if(proceed){_context6.next=38;break}return _context6.abrupt("return");case 38:this.lineHighlighter.highlight(29);_context6.next=41;return this.timer.wait(500);case 41:proceed=
_context6.sent;if(proceed){_context6.next=44;break}return _context6.abrupt("return");case 44:this.lineHighlighter.clear();this.lineHighlighter.highlight(30);_context6.next=48;return this.timer.wait(500);case 48:proceed=_context6.sent;if(proceed){_context6.next=51;break}return _context6.abrupt("return");case 51:this.lineHighlighter.clear();_context6.next=54;return queue.exampleEnqueue(true,this.lineHighlighter,this.timer,this.visualLinkedList);case 54:if(proceed){_context6.next=56;break}return _context6.abrupt("return");
case 56:this.lineHighlighter.highlight(30);_context6.next=59;return this.timer.wait(500);case 59:proceed=_context6.sent;if(proceed){_context6.next=62;break}return _context6.abrupt("return");case 62:this.lineHighlighter.clear();this.finish();case 64:case "end":return _context6.stop()}},_callee6,this)}));function code(){return _code3.apply(this,arguments)}return code}()},{exampleId:4,visualLinkedList:new VisualLinkedList("linked-list-4"),lineHighlighter:new LineHighlighter("code-4"),timer:new Timer,
code:function(){var _code4=_asyncToGenerator(regeneratorRuntime.mark(function _callee8(){var proceed,queue;return regeneratorRuntime.wrap(function _callee8$(_context8){while(1)switch(_context8.prev=_context8.next){case 0:queue=new Queue;queue.exampleDequeue=function(){var _ref4=_asyncToGenerator(regeneratorRuntime.mark(function _callee7(lineHighlighter,timer,visualLinkedList){var value;return regeneratorRuntime.wrap(function _callee7$(_context7){while(1)switch(_context7.prev=_context7.next){case 0:lineHighlighter.highlight(6);
_context7.next=3;return timer.wait(500);case 3:proceed=_context7.sent;if(proceed){_context7.next=6;break}return _context7.abrupt("return");case 6:lineHighlighter.clear();if(this.first){_context7.next=9;break}return _context7.abrupt("return",null);case 9:value=this.first.value;lineHighlighter.highlight(9);_context7.next=13;return timer.wait(500);case 13:proceed=_context7.sent;if(proceed){_context7.next=16;break}return _context7.abrupt("return");case 16:lineHighlighter.clear();lineHighlighter.highlight(12);
_context7.next=20;return timer.wait(500);case 20:proceed=_context7.sent;if(proceed){_context7.next=23;break}return _context7.abrupt("return");case 23:lineHighlighter.clear();if(!(this.first===this.last)){_context7.next=34;break}this.last=null;visualLinkedList.get(this.size-1).removeLastStatus();lineHighlighter.highlight(13);_context7.next=30;return timer.wait(500);case 30:proceed=_context7.sent;if(proceed){_context7.next=33;break}return _context7.abrupt("return");case 33:lineHighlighter.clear();case 34:this.first=
this.first.next;visualLinkedList.get(0).removeFirstStatus();if(this.size>1)visualLinkedList.get(1).setFirstStatus();lineHighlighter.highlight(16);_context7.next=40;return timer.wait(500);case 40:proceed=_context7.sent;if(proceed){_context7.next=43;break}return _context7.abrupt("return");case 43:lineHighlighter.clear();this.size--;lineHighlighter.highlight(18);_context7.next=48;return timer.wait(500);case 48:proceed=_context7.sent;if(proceed){_context7.next=51;break}return _context7.abrupt("return");
case 51:lineHighlighter.clear();lineHighlighter.highlight(20);_context7.next=55;return timer.wait(500);case 55:proceed=_context7.sent;if(proceed){_context7.next=58;break}return _context7.abrupt("return");case 58:lineHighlighter.clear();visualLinkedList.shift();return _context7.abrupt("return",value);case 61:case "end":return _context7.stop()}},_callee7,this)}));return function(_x12,_x13,_x14){return _ref4.apply(this,arguments)}}();this.lineHighlighter.highlight(25);_context8.next=5;return this.timer.wait(500);
case 5:proceed=_context8.sent;if(proceed){_context8.next=8;break}return _context8.abrupt("return");case 8:this.lineHighlighter.clear();queue.enqueue(25);this.visualLinkedList.push(25);this.visualLinkedList.get(0).setFirstStatus();this.visualLinkedList.get(0).setLastStatus();this.lineHighlighter.highlight(28);_context8.next=16;return this.timer.wait(500);case 16:proceed=_context8.sent;if(proceed){_context8.next=19;break}return _context8.abrupt("return");case 19:this.lineHighlighter.clear();queue.enqueue(5);
this.visualLinkedList.push(5);this.visualLinkedList.get(0).removeLastStatus();this.visualLinkedList.get(0).displayArrow();this.visualLinkedList.get(1).setLastStatus();this.lineHighlighter.highlight(29);_context8.next=28;return this.timer.wait(500);case 28:proceed=_context8.sent;if(proceed){_context8.next=31;break}return _context8.abrupt("return");case 31:this.lineHighlighter.clear();queue.enqueue(true);this.visualLinkedList.push(true);this.visualLinkedList.get(1).removeLastStatus();this.visualLinkedList.get(1).displayArrow();
this.visualLinkedList.get(2).setLastStatus();this.lineHighlighter.highlight(30);_context8.next=40;return this.timer.wait(500);case 40:proceed=_context8.sent;if(proceed){_context8.next=43;break}return _context8.abrupt("return");case 43:this.lineHighlighter.clear();this.lineHighlighter.highlight(33);_context8.next=47;return this.timer.wait(500);case 47:proceed=_context8.sent;if(proceed){_context8.next=50;break}return _context8.abrupt("return");case 50:this.lineHighlighter.clear();_context8.next=53;
return queue.exampleDequeue(this.lineHighlighter,this.timer,this.visualLinkedList);case 53:if(proceed){_context8.next=55;break}return _context8.abrupt("return");case 55:this.lineHighlighter.highlight(33);_context8.next=58;return this.timer.wait(500);case 58:proceed=_context8.sent;if(proceed){_context8.next=61;break}return _context8.abrupt("return");case 61:this.lineHighlighter.clear();queue.enqueue(23);this.visualLinkedList.push(23);this.visualLinkedList.get(1).removeLastStatus();this.visualLinkedList.get(1).displayArrow();
this.visualLinkedList.get(2).setLastStatus();this.lineHighlighter.highlight(36);_context8.next=70;return this.timer.wait(500);case 70:proceed=_context8.sent;if(proceed){_context8.next=73;break}return _context8.abrupt("return");case 73:this.lineHighlighter.clear();this.lineHighlighter.highlight(39);_context8.next=77;return this.timer.wait(500);case 77:proceed=_context8.sent;if(proceed){_context8.next=80;break}return _context8.abrupt("return");case 80:this.lineHighlighter.clear();_context8.next=83;
return queue.exampleDequeue(this.lineHighlighter,this.timer,this.visualLinkedList);case 83:if(proceed){_context8.next=85;break}return _context8.abrupt("return");case 85:this.lineHighlighter.highlight(39);_context8.next=88;return this.timer.wait(500);case 88:proceed=_context8.sent;if(proceed){_context8.next=91;break}return _context8.abrupt("return");case 91:this.lineHighlighter.clear();this.lineHighlighter.highlight(40);_context8.next=95;return this.timer.wait(500);case 95:proceed=_context8.sent;if(proceed){_context8.next=
98;break}return _context8.abrupt("return");case 98:this.lineHighlighter.clear();_context8.next=101;return queue.exampleDequeue(this.lineHighlighter,this.timer,this.visualLinkedList);case 101:if(proceed){_context8.next=103;break}return _context8.abrupt("return");case 103:this.lineHighlighter.highlight(40);_context8.next=106;return this.timer.wait(500);case 106:proceed=_context8.sent;if(proceed){_context8.next=109;break}return _context8.abrupt("return");case 109:this.lineHighlighter.clear();this.finish();
case 111:case "end":return _context8.stop()}},_callee8,this)}));function code(){return _code4.apply(this,arguments)}return code}()}];initExamples(config);