function asyncGeneratorStep(gen,resolve,reject,_next,_throw,key,arg){try{var info=gen[key](arg);var value=info.value}catch(error){reject(error);return}if(info.done)resolve(value);else Promise.resolve(value).then(_next,_throw)}
function _asyncToGenerator(fn){return function(){var self=this,args=arguments;return new Promise(function(resolve,reject){var gen=fn.apply(self,args);function _next(value){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"next",value)}function _throw(err){asyncGeneratorStep(gen,resolve,reject,_next,_throw,"throw",err)}_next(undefined)})}}
function _defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor)}}
function _createClass(Constructor,protoProps,staticProps){if(protoProps)_defineProperties(Constructor.prototype,protoProps);if(staticProps)_defineProperties(Constructor,staticProps);Object.defineProperty(Constructor,"prototype",{writable:false});return Constructor}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor))throw new TypeError("Cannot call a class as a function");}var LineHighlighter=InteractiveExample.LineHighlighter;var Timer=InteractiveExample.Timer;
var initExamples=InteractiveExample.initExamples;var VisualTree=InteractiveExample.VisualTree;var VisualLinkedList=InteractiveExample.VisualLinkedList;var VisualArray=InteractiveExample.VisualArray;var Console=InteractiveExample.Console;var CallStack=InteractiveExample.CallStack;var QueueNode=_createClass(function QueueNode(value){_classCallCheck(this,QueueNode);this.value=value;this.next=null});
var Queue=function(){function Queue(){_classCallCheck(this,Queue);this.first=null;this.last=null;this.size=0}_createClass(Queue,[{key:"enqueue",value:function enqueue(value){var newNode=new QueueNode(value);if(!this.first){this.first=newNode;this.last=newNode}else{this.last.next=newNode;this.last=newNode}return++this.size}},{key:"dequeue",value:function dequeue(){if(!this.first)return null;var value=this.first.value;if(this.first===this.last)this.last=null;this.first=this.first.next;this.size--;return value}}]);
return Queue}();var Node=_createClass(function Node(value){_classCallCheck(this,Node);this.value=value;this.left=null;this.right=null});
var BinarySearchTree=function(){function BinarySearchTree(){_classCallCheck(this,BinarySearchTree);this.root=null}_createClass(BinarySearchTree,[{key:"insert",value:function insert(value){var newNode=new Node(value);if(!this.root){this.root=newNode;return this}var current=this.root;while(true){if(value===current.value)return undefined;if(value>current.value){if(!current.right){current.right=newNode;return this}current=current.right}else{if(!current.left){current.left=newNode;return this}current=current.left}}}},
{key:"find",value:function find(value){if(!this.root)return false;var current=this.root;while(current){if(value===current.value)return current;if(value>current.value)current=current.right;else current=current.left}return false}}]);return BinarySearchTree}();
var config=[{exampleId:1,console:new Console("console-1"),visualTree:new VisualTree("binary-search-tree-1",["node"]),visualLinkedList:new VisualLinkedList("queue-1"),visualArray:new VisualArray("visual-array-1",11),lineHighlighter:new LineHighlighter("code-1"),timer:new Timer,code:function(){var _code=_asyncToGenerator(regeneratorRuntime.mark(function _callee2(){var proceed,tree,vysledek;return regeneratorRuntime.wrap(function _callee2$(_context2){while(1)switch(_context2.prev=_context2.next){case 0:tree=
new BinarySearchTree;tree.exampleBFS=function(){var _ref=_asyncToGenerator(regeneratorRuntime.mark(function _callee(lineHighlighter,timer,visualLinkedList,visualTree,visualArray){var queue,data,node;return regeneratorRuntime.wrap(function _callee$(_context){while(1)switch(_context.prev=_context.next){case 0:queue=new Queue;lineHighlighter.highlight(6);_context.next=4;return timer.wait(500);case 4:proceed=_context.sent;if(proceed){_context.next=7;break}return _context.abrupt("return");case 7:lineHighlighter.clear();
data=[];lineHighlighter.highlight(8);_context.next=12;return timer.wait(500);case 12:proceed=_context.sent;if(proceed){_context.next=15;break}return _context.abrupt("return");case 15:lineHighlighter.clear();queue.enqueue(this.root);visualLinkedList.push(this.root.value);visualLinkedList.get(0).setFirstStatus();visualLinkedList.get(0).setLastStatus();lineHighlighter.highlight(11);_context.next=23;return timer.wait(500);case 23:proceed=_context.sent;if(proceed){_context.next=26;break}return _context.abrupt("return");
case 26:lineHighlighter.clear();lineHighlighter.highlight(14);_context.next=30;return timer.wait(500);case 30:proceed=_context.sent;if(proceed){_context.next=33;break}return _context.abrupt("return");case 33:lineHighlighter.clear();case 34:if(!(queue.size>0)){_context.next=111;break}node=queue.dequeue();visualLinkedList.shift();if(visualLinkedList.length>0)visualLinkedList.get(0).setFirstStatus();visualTree.setPointerToNode("node",node.value);lineHighlighter.highlight(16);_context.next=42;return timer.wait(500);
case 42:proceed=_context.sent;if(proceed){_context.next=45;break}return _context.abrupt("return");case 45:lineHighlighter.clear();data.push(node.value);visualArray.pushItem(node.value);lineHighlighter.highlight(18);_context.next=51;return timer.wait(500);case 51:proceed=_context.sent;if(proceed){_context.next=54;break}return _context.abrupt("return");case 54:lineHighlighter.clear();if(!node.left){_context.next=71;break}queue.enqueue(node.left);if(visualLinkedList.length>0)visualLinkedList.get(visualLinkedList.length-
1).removeLastStatus();visualLinkedList.push(node.left.value);visualLinkedList.get(visualLinkedList.length-1).setLastStatus();if(visualLinkedList.length===1)visualLinkedList.get(0).setFirstStatus();if(visualLinkedList.length>1)visualLinkedList.get(visualLinkedList.length-2).displayArrow();lineHighlighter.highlight(21);_context.next=65;return timer.wait(500);case 65:proceed=_context.sent;if(proceed){_context.next=68;break}return _context.abrupt("return");case 68:lineHighlighter.clear();_context.next=
78;break;case 71:lineHighlighter.highlight(21);_context.next=74;return timer.wait(500);case 74:proceed=_context.sent;if(proceed){_context.next=77;break}return _context.abrupt("return");case 77:lineHighlighter.clear();case 78:if(!node.right){_context.next=94;break}queue.enqueue(node.right);if(visualLinkedList.length>0)visualLinkedList.get(visualLinkedList.length-1).removeLastStatus();visualLinkedList.push(node.right.value);visualLinkedList.get(visualLinkedList.length-1).setLastStatus();if(visualLinkedList.length===
1)visualLinkedList.get(0).setFirstStatus();if(visualLinkedList.length>1)visualLinkedList.get(visualLinkedList.length-2).displayArrow();lineHighlighter.highlight(22);_context.next=88;return timer.wait(500);case 88:proceed=_context.sent;if(proceed){_context.next=91;break}return _context.abrupt("return");case 91:lineHighlighter.clear();_context.next=101;break;case 94:lineHighlighter.highlight(22);_context.next=97;return timer.wait(500);case 97:proceed=_context.sent;if(proceed){_context.next=100;break}return _context.abrupt("return");
case 100:lineHighlighter.clear();case 101:visualTree.hidePointer("node");lineHighlighter.highlight(14);_context.next=105;return timer.wait(500);case 105:proceed=_context.sent;if(proceed){_context.next=108;break}return _context.abrupt("return");case 108:lineHighlighter.clear();_context.next=34;break;case 111:lineHighlighter.highlight(26);_context.next=114;return timer.wait(500);case 114:proceed=_context.sent;if(proceed){_context.next=117;break}return _context.abrupt("return");case 117:lineHighlighter.clear();
return _context.abrupt("return",data);case 119:case "end":return _context.stop()}},_callee,this)}));return function(_x,_x2,_x3,_x4,_x5){return _ref.apply(this,arguments)}}();this.lineHighlighter.highlight(31);_context2.next=5;return this.timer.wait(500);case 5:proceed=_context2.sent;if(proceed){_context2.next=8;break}return _context2.abrupt("return");case 8:this.lineHighlighter.clear();tree.insert(10).insert(5).insert(16).insert(13).insert(6).insert(2);tree.insert(17).insert(7).insert(3).insert(14).insert(11);
this.visualTree.insert(10).insert(5).insert(16).insert(13).insert(6).insert(2);this.lineHighlighter.highlight(32);_context2.next=15;return this.timer.wait(500);case 15:proceed=_context2.sent;if(proceed){_context2.next=18;break}return _context2.abrupt("return");case 18:this.lineHighlighter.clear();this.visualTree.insert(17).insert(7).insert(3).insert(14).insert(11);this.lineHighlighter.highlight(33);_context2.next=23;return this.timer.wait(500);case 23:proceed=_context2.sent;if(proceed){_context2.next=
26;break}return _context2.abrupt("return");case 26:this.lineHighlighter.clear();this.lineHighlighter.highlight(36);_context2.next=30;return this.timer.wait(500);case 30:proceed=_context2.sent;if(proceed){_context2.next=33;break}return _context2.abrupt("return");case 33:this.lineHighlighter.clear();_context2.next=36;return tree.exampleBFS(this.lineHighlighter,this.timer,this.visualLinkedList,this.visualTree,this.visualArray);case 36:vysledek=_context2.sent;if(proceed){_context2.next=39;break}return _context2.abrupt("return");
case 39:this.lineHighlighter.highlight(36);_context2.next=42;return this.timer.wait(500);case 42:proceed=_context2.sent;if(proceed){_context2.next=45;break}return _context2.abrupt("return");case 45:this.lineHighlighter.clear();this.console.log("Tree se proch\u00e1zel v tomto po\u0159ad\u00ed:");this.lineHighlighter.highlight(37);_context2.next=50;return this.timer.wait(500);case 50:proceed=_context2.sent;if(proceed){_context2.next=53;break}return _context2.abrupt("return");case 53:this.lineHighlighter.clear();
this.console.log("["+vysledek+"]");this.lineHighlighter.highlight(38);_context2.next=58;return this.timer.wait(500);case 58:proceed=_context2.sent;if(proceed){_context2.next=61;break}return _context2.abrupt("return");case 61:this.lineHighlighter.clear();this.finish();case 63:case "end":return _context2.stop()}},_callee2,this)}));function code(){return _code.apply(this,arguments)}return code}()},{exampleId:2,console:new Console("console-2"),visualTree:new VisualTree("binary-search-tree-2",["node"]),
visualArray:new VisualArray("visual-array-2",11),lineHighlighter:new LineHighlighter("code-2"),callStack:new CallStack("call-stack-1"),timer:new Timer,code:function(){var _code2=_asyncToGenerator(regeneratorRuntime.mark(function _callee5(){var proceed,tree,vysledek;return regeneratorRuntime.wrap(function _callee5$(_context5){while(1)switch(_context5.prev=_context5.next){case 0:tree=new BinarySearchTree;tree.exampleDFSPreOrder=function(){var _ref2=_asyncToGenerator(regeneratorRuntime.mark(function _callee4(lineHighlighter,
timer,visualTree,visualArray,callStack){var data,traverse;return regeneratorRuntime.wrap(function _callee4$(_context4){while(1)switch(_context4.prev=_context4.next){case 0:callStack.push("DFSPreOrder");data=[];lineHighlighter.highlight(6);_context4.next=5;return timer.wait(500);case 5:proceed=_context4.sent;if(proceed){_context4.next=8;break}return _context4.abrupt("return");case 8:lineHighlighter.clear();traverse=function(){var _ref3=_asyncToGenerator(regeneratorRuntime.mark(function _callee3(node){return regeneratorRuntime.wrap(function _callee3$(_context3){while(1)switch(_context3.prev=
_context3.next){case 0:callStack.push("traverse");visualTree.setPointerToNode("node",node.value);data.push(node.value);visualArray.pushItem(node.value);lineHighlighter.highlight(11);_context3.next=7;return timer.wait(500);case 7:proceed=_context3.sent;if(proceed){_context3.next=10;break}return _context3.abrupt("return");case 10:lineHighlighter.clear();if(!node.left){_context3.next=33;break}lineHighlighter.highlight(13);_context3.next=15;return timer.wait(500);case 15:proceed=_context3.sent;if(proceed){_context3.next=
18;break}return _context3.abrupt("return");case 18:lineHighlighter.clear();_context3.next=21;return traverse(node.left);case 21:if(proceed){_context3.next=23;break}return _context3.abrupt("return");case 23:visualTree.setPointerToNode("node",node.value);lineHighlighter.highlight(13);_context3.next=27;return timer.wait(500);case 27:proceed=_context3.sent;if(proceed){_context3.next=30;break}return _context3.abrupt("return");case 30:lineHighlighter.clear();_context3.next=40;break;case 33:lineHighlighter.highlight(13);
_context3.next=36;return timer.wait(500);case 36:proceed=_context3.sent;if(proceed){_context3.next=39;break}return _context3.abrupt("return");case 39:lineHighlighter.clear();case 40:if(!node.right){_context3.next=62;break}lineHighlighter.highlight(15);_context3.next=44;return timer.wait(500);case 44:proceed=_context3.sent;if(proceed){_context3.next=47;break}return _context3.abrupt("return");case 47:lineHighlighter.clear();_context3.next=50;return traverse(node.right);case 50:if(proceed){_context3.next=
52;break}return _context3.abrupt("return");case 52:visualTree.setPointerToNode("node",node.value);lineHighlighter.highlight(15);_context3.next=56;return timer.wait(500);case 56:proceed=_context3.sent;if(proceed){_context3.next=59;break}return _context3.abrupt("return");case 59:lineHighlighter.clear();_context3.next=69;break;case 62:lineHighlighter.highlight(15);_context3.next=65;return timer.wait(500);case 65:proceed=_context3.sent;if(proceed){_context3.next=68;break}return _context3.abrupt("return");
case 68:lineHighlighter.clear();case 69:visualTree.hidePointer("node");callStack.pop();case 71:case "end":return _context3.stop()}},_callee3)}));return function traverse(_x11){return _ref3.apply(this,arguments)}}();lineHighlighter.highlight(9);_context4.next=13;return timer.wait(500);case 13:proceed=_context4.sent;if(proceed){_context4.next=16;break}return _context4.abrupt("return");case 16:lineHighlighter.clear();lineHighlighter.highlight(19);_context4.next=20;return timer.wait(500);case 20:proceed=
_context4.sent;if(proceed){_context4.next=23;break}return _context4.abrupt("return");case 23:lineHighlighter.clear();_context4.next=26;return traverse(this.root);case 26:if(proceed){_context4.next=28;break}return _context4.abrupt("return");case 28:lineHighlighter.highlight(19);_context4.next=31;return timer.wait(500);case 31:proceed=_context4.sent;if(proceed){_context4.next=34;break}return _context4.abrupt("return");case 34:lineHighlighter.clear();lineHighlighter.highlight(22);_context4.next=38;return timer.wait(500);
case 38:proceed=_context4.sent;if(proceed){_context4.next=41;break}return _context4.abrupt("return");case 41:lineHighlighter.clear();callStack.pop();return _context4.abrupt("return",data);case 44:case "end":return _context4.stop()}},_callee4,this)}));return function(_x6,_x7,_x8,_x9,_x10){return _ref2.apply(this,arguments)}}();this.lineHighlighter.highlight(27);_context5.next=5;return this.timer.wait(500);case 5:proceed=_context5.sent;if(proceed){_context5.next=8;break}return _context5.abrupt("return");
case 8:this.lineHighlighter.clear();tree.insert(10).insert(5).insert(16).insert(13).insert(6).insert(2);tree.insert(17).insert(7).insert(3).insert(14).insert(11);this.visualTree.insert(10).insert(5).insert(16).insert(13).insert(6).insert(2);this.lineHighlighter.highlight(28);_context5.next=15;return this.timer.wait(500);case 15:proceed=_context5.sent;if(proceed){_context5.next=18;break}return _context5.abrupt("return");case 18:this.lineHighlighter.clear();this.visualTree.insert(17).insert(7).insert(3).insert(14).insert(11);
this.lineHighlighter.highlight(29);_context5.next=23;return this.timer.wait(500);case 23:proceed=_context5.sent;if(proceed){_context5.next=26;break}return _context5.abrupt("return");case 26:this.lineHighlighter.clear();this.lineHighlighter.highlight(32);_context5.next=30;return this.timer.wait(500);case 30:proceed=_context5.sent;if(proceed){_context5.next=33;break}return _context5.abrupt("return");case 33:this.lineHighlighter.clear();_context5.next=36;return tree.exampleDFSPreOrder(this.lineHighlighter,
this.timer,this.visualTree,this.visualArray,this.callStack);case 36:vysledek=_context5.sent;if(proceed){_context5.next=39;break}return _context5.abrupt("return");case 39:this.lineHighlighter.highlight(32);_context5.next=42;return this.timer.wait(500);case 42:proceed=_context5.sent;if(proceed){_context5.next=45;break}return _context5.abrupt("return");case 45:this.lineHighlighter.clear();this.console.log("Tree se proch\u00e1zel v tomto po\u0159ad\u00ed:");this.lineHighlighter.highlight(33);_context5.next=
50;return this.timer.wait(500);case 50:proceed=_context5.sent;if(proceed){_context5.next=53;break}return _context5.abrupt("return");case 53:this.lineHighlighter.clear();this.console.log("["+vysledek+"]");this.lineHighlighter.highlight(34);_context5.next=58;return this.timer.wait(500);case 58:proceed=_context5.sent;if(proceed){_context5.next=61;break}return _context5.abrupt("return");case 61:this.lineHighlighter.clear();this.finish();case 63:case "end":return _context5.stop()}},_callee5,this)}));function code(){return _code2.apply(this,
arguments)}return code}()},{exampleId:3,console:new Console("console-3"),visualTree:new VisualTree("binary-search-tree-3",["node"]),visualArray:new VisualArray("visual-array-3",11),lineHighlighter:new LineHighlighter("code-3"),callStack:new CallStack("call-stack-2"),timer:new Timer,code:function(){var _code3=_asyncToGenerator(regeneratorRuntime.mark(function _callee8(){var proceed,tree,vysledek;return regeneratorRuntime.wrap(function _callee8$(_context8){while(1)switch(_context8.prev=_context8.next){case 0:tree=
new BinarySearchTree;tree.exampleDFSPostOrder=function(){var _ref4=_asyncToGenerator(regeneratorRuntime.mark(function _callee7(lineHighlighter,timer,visualTree,visualArray,callStack){var data,traverse;return regeneratorRuntime.wrap(function _callee7$(_context7){while(1)switch(_context7.prev=_context7.next){case 0:callStack.push("DFSPreOrder");data=[];lineHighlighter.highlight(5);_context7.next=5;return timer.wait(500);case 5:proceed=_context7.sent;if(proceed){_context7.next=8;break}return _context7.abrupt("return");
case 8:lineHighlighter.clear();traverse=function(){var _ref5=_asyncToGenerator(regeneratorRuntime.mark(function _callee6(node){return regeneratorRuntime.wrap(function _callee6$(_context6){while(1)switch(_context6.prev=_context6.next){case 0:callStack.push("traverse");visualTree.setPointerToNode("node",node.value);if(!node.left){_context6.next=24;break}lineHighlighter.highlight(8);_context6.next=6;return timer.wait(500);case 6:proceed=_context6.sent;if(proceed){_context6.next=9;break}return _context6.abrupt("return");
case 9:lineHighlighter.clear();_context6.next=12;return traverse(node.left);case 12:if(proceed){_context6.next=14;break}return _context6.abrupt("return");case 14:visualTree.setPointerToNode("node",node.value);lineHighlighter.highlight(8);_context6.next=18;return timer.wait(500);case 18:proceed=_context6.sent;if(proceed){_context6.next=21;break}return _context6.abrupt("return");case 21:lineHighlighter.clear();_context6.next=31;break;case 24:lineHighlighter.highlight(8);_context6.next=27;return timer.wait(500);
case 27:proceed=_context6.sent;if(proceed){_context6.next=30;break}return _context6.abrupt("return");case 30:lineHighlighter.clear();case 31:if(!node.right){_context6.next=53;break}lineHighlighter.highlight(9);_context6.next=35;return timer.wait(500);case 35:proceed=_context6.sent;if(proceed){_context6.next=38;break}return _context6.abrupt("return");case 38:lineHighlighter.clear();_context6.next=41;return traverse(node.right);case 41:if(proceed){_context6.next=43;break}return _context6.abrupt("return");
case 43:visualTree.setPointerToNode("node",node.value);lineHighlighter.highlight(9);_context6.next=47;return timer.wait(500);case 47:proceed=_context6.sent;if(proceed){_context6.next=50;break}return _context6.abrupt("return");case 50:lineHighlighter.clear();_context6.next=60;break;case 53:lineHighlighter.highlight(9);_context6.next=56;return timer.wait(500);case 56:proceed=_context6.sent;if(proceed){_context6.next=59;break}return _context6.abrupt("return");case 59:lineHighlighter.clear();case 60:data.push(node.value);
visualArray.pushItem(node.value);lineHighlighter.highlight(11);_context6.next=65;return timer.wait(500);case 65:proceed=_context6.sent;if(proceed){_context6.next=68;break}return _context6.abrupt("return");case 68:lineHighlighter.clear();visualTree.hidePointer("node");callStack.pop();case 71:case "end":return _context6.stop()}},_callee6)}));return function traverse(_x17){return _ref5.apply(this,arguments)}}();lineHighlighter.highlight(7);_context7.next=13;return timer.wait(500);case 13:proceed=_context7.sent;
if(proceed){_context7.next=16;break}return _context7.abrupt("return");case 16:lineHighlighter.clear();lineHighlighter.highlight(14);_context7.next=20;return timer.wait(500);case 20:proceed=_context7.sent;if(proceed){_context7.next=23;break}return _context7.abrupt("return");case 23:lineHighlighter.clear();_context7.next=26;return traverse(this.root);case 26:if(proceed){_context7.next=28;break}return _context7.abrupt("return");case 28:lineHighlighter.highlight(14);_context7.next=31;return timer.wait(500);
case 31:proceed=_context7.sent;if(proceed){_context7.next=34;break}return _context7.abrupt("return");case 34:lineHighlighter.clear();lineHighlighter.highlight(15);_context7.next=38;return timer.wait(500);case 38:proceed=_context7.sent;if(proceed){_context7.next=41;break}return _context7.abrupt("return");case 41:lineHighlighter.clear();callStack.pop();return _context7.abrupt("return",data);case 44:case "end":return _context7.stop()}},_callee7,this)}));return function(_x12,_x13,_x14,_x15,_x16){return _ref4.apply(this,
arguments)}}();this.lineHighlighter.highlight(20);_context8.next=5;return this.timer.wait(500);case 5:proceed=_context8.sent;if(proceed){_context8.next=8;break}return _context8.abrupt("return");case 8:this.lineHighlighter.clear();tree.insert(10).insert(5).insert(16).insert(13).insert(6).insert(2);tree.insert(17).insert(7).insert(3).insert(14).insert(11);this.visualTree.insert(10).insert(5).insert(16).insert(13).insert(6).insert(2);this.lineHighlighter.highlight(21);_context8.next=15;return this.timer.wait(500);
case 15:proceed=_context8.sent;if(proceed){_context8.next=18;break}return _context8.abrupt("return");case 18:this.lineHighlighter.clear();this.visualTree.insert(17).insert(7).insert(3).insert(14).insert(11);this.lineHighlighter.highlight(22);_context8.next=23;return this.timer.wait(500);case 23:proceed=_context8.sent;if(proceed){_context8.next=26;break}return _context8.abrupt("return");case 26:this.lineHighlighter.clear();this.lineHighlighter.highlight(25);_context8.next=30;return this.timer.wait(500);
case 30:proceed=_context8.sent;if(proceed){_context8.next=33;break}return _context8.abrupt("return");case 33:this.lineHighlighter.clear();_context8.next=36;return tree.exampleDFSPostOrder(this.lineHighlighter,this.timer,this.visualTree,this.visualArray,this.callStack);case 36:vysledek=_context8.sent;if(proceed){_context8.next=39;break}return _context8.abrupt("return");case 39:this.lineHighlighter.highlight(25);_context8.next=42;return this.timer.wait(500);case 42:proceed=_context8.sent;if(proceed){_context8.next=
45;break}return _context8.abrupt("return");case 45:this.lineHighlighter.clear();this.console.log("Tree se proch\u00e1zel v tomto po\u0159ad\u00ed:");this.lineHighlighter.highlight(26);_context8.next=50;return this.timer.wait(500);case 50:proceed=_context8.sent;if(proceed){_context8.next=53;break}return _context8.abrupt("return");case 53:this.lineHighlighter.clear();this.console.log("["+vysledek+"]");this.lineHighlighter.highlight(27);_context8.next=58;return this.timer.wait(500);case 58:proceed=_context8.sent;
if(proceed){_context8.next=61;break}return _context8.abrupt("return");case 61:this.lineHighlighter.clear();this.finish();case 63:case "end":return _context8.stop()}},_callee8,this)}));function code(){return _code3.apply(this,arguments)}return code}()},{exampleId:4,console:new Console("console-4"),visualTree:new VisualTree("binary-search-tree-4",["node"]),visualArray:new VisualArray("visual-array-4",11),lineHighlighter:new LineHighlighter("code-4"),callStack:new CallStack("call-stack-3"),timer:new Timer,
code:function(){var _code4=_asyncToGenerator(regeneratorRuntime.mark(function _callee11(){var proceed,tree,vysledek;return regeneratorRuntime.wrap(function _callee11$(_context11){while(1)switch(_context11.prev=_context11.next){case 0:tree=new BinarySearchTree;tree.exampleDFSInOrder=function(){var _ref6=_asyncToGenerator(regeneratorRuntime.mark(function _callee10(lineHighlighter,timer,visualTree,visualArray,callStack){var data,traverse;return regeneratorRuntime.wrap(function _callee10$(_context10){while(1)switch(_context10.prev=
_context10.next){case 0:callStack.push("DFSPreOrder");data=[];lineHighlighter.highlight(5);_context10.next=5;return timer.wait(500);case 5:proceed=_context10.sent;if(proceed){_context10.next=8;break}return _context10.abrupt("return");case 8:lineHighlighter.clear();traverse=function(){var _ref7=_asyncToGenerator(regeneratorRuntime.mark(function _callee9(node){return regeneratorRuntime.wrap(function _callee9$(_context9){while(1)switch(_context9.prev=_context9.next){case 0:callStack.push("traverse");
visualTree.setPointerToNode("node",node.value);if(!node.left){_context9.next=24;break}lineHighlighter.highlight(8);_context9.next=6;return timer.wait(500);case 6:proceed=_context9.sent;if(proceed){_context9.next=9;break}return _context9.abrupt("return");case 9:lineHighlighter.clear();_context9.next=12;return traverse(node.left);case 12:if(proceed){_context9.next=14;break}return _context9.abrupt("return");case 14:visualTree.setPointerToNode("node",node.value);lineHighlighter.highlight(8);_context9.next=
18;return timer.wait(500);case 18:proceed=_context9.sent;if(proceed){_context9.next=21;break}return _context9.abrupt("return");case 21:lineHighlighter.clear();_context9.next=31;break;case 24:lineHighlighter.highlight(8);_context9.next=27;return timer.wait(500);case 27:proceed=_context9.sent;if(proceed){_context9.next=30;break}return _context9.abrupt("return");case 30:lineHighlighter.clear();case 31:data.push(node.value);visualArray.pushItem(node.value);lineHighlighter.highlight(10);_context9.next=
36;return timer.wait(500);case 36:proceed=_context9.sent;if(proceed){_context9.next=39;break}return _context9.abrupt("return");case 39:lineHighlighter.clear();if(!node.right){_context9.next=62;break}lineHighlighter.highlight(11);_context9.next=44;return timer.wait(500);case 44:proceed=_context9.sent;if(proceed){_context9.next=47;break}return _context9.abrupt("return");case 47:lineHighlighter.clear();_context9.next=50;return traverse(node.right);case 50:if(proceed){_context9.next=52;break}return _context9.abrupt("return");
case 52:visualTree.setPointerToNode("node",node.value);lineHighlighter.highlight(11);_context9.next=56;return timer.wait(500);case 56:proceed=_context9.sent;if(proceed){_context9.next=59;break}return _context9.abrupt("return");case 59:lineHighlighter.clear();_context9.next=69;break;case 62:lineHighlighter.highlight(11);_context9.next=65;return timer.wait(500);case 65:proceed=_context9.sent;if(proceed){_context9.next=68;break}return _context9.abrupt("return");case 68:lineHighlighter.clear();case 69:visualTree.hidePointer("node");
callStack.pop();case 71:case "end":return _context9.stop()}},_callee9)}));return function traverse(_x23){return _ref7.apply(this,arguments)}}();lineHighlighter.highlight(7);_context10.next=13;return timer.wait(500);case 13:proceed=_context10.sent;if(proceed){_context10.next=16;break}return _context10.abrupt("return");case 16:lineHighlighter.clear();lineHighlighter.highlight(14);_context10.next=20;return timer.wait(500);case 20:proceed=_context10.sent;if(proceed){_context10.next=23;break}return _context10.abrupt("return");
case 23:lineHighlighter.clear();_context10.next=26;return traverse(this.root);case 26:if(proceed){_context10.next=28;break}return _context10.abrupt("return");case 28:lineHighlighter.highlight(14);_context10.next=31;return timer.wait(500);case 31:proceed=_context10.sent;if(proceed){_context10.next=34;break}return _context10.abrupt("return");case 34:lineHighlighter.clear();lineHighlighter.highlight(15);_context10.next=38;return timer.wait(500);case 38:proceed=_context10.sent;if(proceed){_context10.next=
41;break}return _context10.abrupt("return");case 41:lineHighlighter.clear();callStack.pop();return _context10.abrupt("return",data);case 44:case "end":return _context10.stop()}},_callee10,this)}));return function(_x18,_x19,_x20,_x21,_x22){return _ref6.apply(this,arguments)}}();this.lineHighlighter.highlight(20);_context11.next=5;return this.timer.wait(500);case 5:proceed=_context11.sent;if(proceed){_context11.next=8;break}return _context11.abrupt("return");case 8:this.lineHighlighter.clear();tree.insert(10).insert(5).insert(16).insert(13).insert(6).insert(2);
tree.insert(17).insert(7).insert(3).insert(14).insert(11);this.visualTree.insert(10).insert(5).insert(16).insert(13).insert(6).insert(2);this.lineHighlighter.highlight(21);_context11.next=15;return this.timer.wait(500);case 15:proceed=_context11.sent;if(proceed){_context11.next=18;break}return _context11.abrupt("return");case 18:this.lineHighlighter.clear();this.visualTree.insert(17).insert(7).insert(3).insert(14).insert(11);this.lineHighlighter.highlight(22);_context11.next=23;return this.timer.wait(500);
case 23:proceed=_context11.sent;if(proceed){_context11.next=26;break}return _context11.abrupt("return");case 26:this.lineHighlighter.clear();this.lineHighlighter.highlight(25);_context11.next=30;return this.timer.wait(500);case 30:proceed=_context11.sent;if(proceed){_context11.next=33;break}return _context11.abrupt("return");case 33:this.lineHighlighter.clear();_context11.next=36;return tree.exampleDFSInOrder(this.lineHighlighter,this.timer,this.visualTree,this.visualArray,this.callStack);case 36:vysledek=
_context11.sent;if(proceed){_context11.next=39;break}return _context11.abrupt("return");case 39:this.lineHighlighter.highlight(25);_context11.next=42;return this.timer.wait(500);case 42:proceed=_context11.sent;if(proceed){_context11.next=45;break}return _context11.abrupt("return");case 45:this.lineHighlighter.clear();this.console.log("Tree se proch\u00e1zel v tomto po\u0159ad\u00ed:");this.lineHighlighter.highlight(26);_context11.next=50;return this.timer.wait(500);case 50:proceed=_context11.sent;
if(proceed){_context11.next=53;break}return _context11.abrupt("return");case 53:this.lineHighlighter.clear();this.console.log("["+vysledek+"]");this.lineHighlighter.highlight(27);_context11.next=58;return this.timer.wait(500);case 58:proceed=_context11.sent;if(proceed){_context11.next=61;break}return _context11.abrupt("return");case 61:this.lineHighlighter.clear();this.finish();case 63:case "end":return _context11.stop()}},_callee11,this)}));function code(){return _code4.apply(this,arguments)}return code}()}];
initExamples(config);